"""Download self-hosted webfonts (latin/latin-ext woff2) from Google Fonts and
emit src/fonts.css with local @font-face rules. Local-first: run once; the
woff2 files and fonts.css are committed so the app needs no font CDN.

  python scripts/fetch_selfhost_fonts.py
"""
import os
import re
import subprocess

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # frontend/
FONTS_DIR = os.path.join(HERE, "src", "assets", "fonts")
os.makedirs(FONTS_DIR, exist_ok=True)

UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

# (css2 family spec, filename prefix, wanted subsets)
SPECS = [
    ("EB+Garamond:ital,wght@0,400;0,500;0,600;1,400", "ebgaramond", ["latin", "latin-ext"]),
    ("Cinzel:wght@600;700", "cinzel", ["latin"]),
    ("Pinyon+Script", "pinyonscript", ["latin"]),
]

BLOCK = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", re.S)


def curl(url, out=None):
    args = ["curl", "-s", "-A", UA, url]
    if out:
        subprocess.run(args + ["-o", out], check=True)
        return None
    return subprocess.run(args, check=True, capture_output=True, text=True).stdout


out_css = ["/* Self-hosted webfonts — generated by scripts/fetch_selfhost_fonts.py */"]
count = 0
for spec, prefix, subsets in SPECS:
    css = curl(f"https://fonts.googleapis.com/css2?family={spec}&display=swap")
    for subset, block in BLOCK.findall(css):
        if subset not in subsets:
            continue
        weight = (re.search(r"font-weight:\s*(\d+)", block) or ["", "400"])[1]
        italic = "italic" in (re.search(r"font-style:\s*(\w+)", block) or ["", ""])[1]
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)
        fn = f"{prefix}-{weight}{'-italic' if italic else ''}-{subset}.woff2"
        curl(url, out=os.path.join(FONTS_DIR, fn))
        out_css.append(block.replace(url, f"./assets/fonts/{fn}").strip())
        count += 1

with open(os.path.join(HERE, "src", "fonts.css"), "w") as fh:
    fh.write("\n".join(out_css) + "\n")
print(f"wrote src/fonts.css with {count} faces")
