"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-25 09:02:46.462719
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('pen_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('biography', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authors_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_authors_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_authors_pen_name'), ['pen_name'], unique=False)

    op.create_table('integration_points',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('type', sa.Enum('LOGOSFORGE', 'SUPERVOID_MOVIES', 'AI_LAB', 'ARCHIVE_KNOWLEDGE_GRAPH', 'OTHER', name='integrationpointtype'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'DISABLED', name='integrationpointstatus'), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_points_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_points_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_points_type'), ['type'], unique=False)

    op.create_table('knowledge_entities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.Enum('CHARACTER', 'PLACE', 'THEME', 'MOTIF', 'ORGANIZATION', 'WORK', 'PERSON', 'PERIOD', 'OTHER', name='entitykind'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=220), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extras', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_entities_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_entities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_entities_slug'), ['slug'], unique=True)

    op.create_table('public_media_assets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='mediaassettype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=False),
    sa.Column('poster_image', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('loop', sa.Boolean(), nullable=False),
    sa.Column('credits', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('public_visibility', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('public_media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_media_assets_public_visibility'), ['public_visibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_media_assets_type'), ['type'], unique=False)

    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EDITOR', 'REVIEWER', 'PRODUCTION_MANAGER', 'MARKETING', 'ARCHIVE_READER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('knowledge_relationships',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('RELATED_TO', 'INFLUENCES', 'DESCENDS_FROM', 'CONTRASTS_WITH', 'INHABITS', 'AUTHORED', 'PART_OF', 'SIBLING_OF', 'MENTOR_OF', 'ADAPTS', 'OTHER', name='relationshipkind'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_entities.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_relationships_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relationships_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relationships_target_id'), ['target_id'], unique=False)

    op.create_table('works',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('work_type', sa.Enum('BOOK', 'GRAPHIC_NOVEL', 'NOVELLA', 'ANTHOLOGY', 'ART_BOOK', 'ESSAY', 'ADAPTATION_CANDIDATE', 'OTHER', name='worktype'), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sa.Enum('CONCEPT', 'PLANNED', 'IN_DEVELOPMENT', 'IN_PRODUCTION', 'PUBLISHED', 'ON_HOLD', 'CANCELLED', 'ARCHIVED', name='workstatus'), nullable=False),
    sa.Column('synopsis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('internal_pitch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_audience', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_works_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_work_type'), ['work_type'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('event_type', sa.Enum('ANNOUNCEMENT', 'COVER_REVEAL', 'PREORDER', 'RELEASE', 'REPRINT', 'LAUNCH_EVENT', 'SIGNING', 'OTHER', name='calendareventtype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='calendareventstatus'), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_work_id'), ['work_id'], unique=False)

    op.create_table('graphic_novel_productions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('script_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('storyboard_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('character_design_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('environment_design_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('page_layout_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('lettering_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('coloring_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('final_files_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graphic_novel_productions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graphic_novel_productions_script_status'), ['script_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_graphic_novel_productions_work_id'), ['work_id'], unique=True)

    op.create_table('manuscripts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('synopsis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_type', sa.Enum('BOOK', 'GRAPHIC_NOVEL', 'NOVELLA', 'ANTHOLOGY', 'ART_BOOK', 'ESSAY', 'ADAPTATION_CANDIDATE', 'OTHER', name='worktype'), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'DEVELOPMENT_EDITING', 'COPY_EDITING', 'PROOFREADING', 'LAYOUT', 'COVER_DESIGN', 'PREPRESS', 'PUBLISHED', 'ARCHIVED', name='workflowstatus'), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('draft_status', sa.Enum('OUTLINE', 'FIRST_DRAFT', 'REVISED_DRAFT', 'FINAL_DRAFT', 'DELIVERED', name='draftstatus'), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('file_format', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manuscripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manuscripts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuscripts_draft_status'), ['draft_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuscripts_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuscripts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuscripts_submission_date'), ['submission_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuscripts_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuscripts_work_id'), ['work_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuscripts_work_type'), ['work_type'], unique=False)

    op.create_table('published_works',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('public_synopsis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'UNLISTED', 'ARCHIVED', name='publishedstatus'), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('author_credit', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('artist_credit', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('music_track_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_intro_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['music_track_id'], ['public_media_assets.id'], ),
    sa.ForeignKeyConstraint(['source_work_id'], ['works.id'], ),
    sa.ForeignKeyConstraint(['video_intro_id'], ['public_media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('published_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_works_publication_date'), ['publication_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_works_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_published_works_source_work_id'), ['source_work_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_works_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_works_title'), ['title'], unique=False)

    op.create_table('rights',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('territory', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('print_rights', sa.Enum('AVAILABLE', 'RESERVED', 'OPTIONED', 'LICENSED', 'SOLD', 'NOT_APPLICABLE', name='rightstatus'), nullable=False),
    sa.Column('ebook_rights', sa.Enum('AVAILABLE', 'RESERVED', 'OPTIONED', 'LICENSED', 'SOLD', 'NOT_APPLICABLE', name='rightstatus'), nullable=False),
    sa.Column('audiobook_rights', sa.Enum('AVAILABLE', 'RESERVED', 'OPTIONED', 'LICENSED', 'SOLD', 'NOT_APPLICABLE', name='rightstatus'), nullable=False),
    sa.Column('film_rights', sa.Enum('AVAILABLE', 'RESERVED', 'OPTIONED', 'LICENSED', 'SOLD', 'NOT_APPLICABLE', name='rightstatus'), nullable=False),
    sa.Column('adaptation_rights', sa.Enum('AVAILABLE', 'RESERVED', 'OPTIONED', 'LICENSED', 'SOLD', 'NOT_APPLICABLE', name='rightstatus'), nullable=False),
    sa.Column('merchandising_rights', sa.Enum('AVAILABLE', 'RESERVED', 'OPTIONED', 'LICENSED', 'SOLD', 'NOT_APPLICABLE', name='rightstatus'), nullable=False),
    sa.Column('holder', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rights_expiration_date'), ['expiration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_territory'), ['territory'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_work_id'), ['work_id'], unique=False)

    op.create_table('ai_insights',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feature', sa.Enum('SUMMARIZE', 'STYLE_ANALYSIS', 'EDITORIAL_SUGGESTIONS', 'SEMANTIC_TAGS', 'CONSISTENCY_CHECK', name='aifeature'), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_insights_feature'), ['feature'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_manuscript_id'), ['manuscript_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploader_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('MANUSCRIPT_DRAFT', 'EDITOR_MARKED_COPY', 'COVER_ARTWORK', 'PROOF', 'CONTRACT_SCAN', 'OTHER', name='attachmentkind'), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_manuscript_id'), ['manuscript_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_uploader_id'), ['uploader_id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'SIGNED', 'TERMINATED', name='contractstatus'), nullable=False),
    sa.Column('advance_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('royalty_rate', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('rights_territory', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_expiration_date'), ['expiration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_manuscript_id'), ['manuscript_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_rights_territory'), ['rights_territory'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_work_id'), ['work_id'], unique=False)

    op.create_table('editorial_notes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('GENERAL', 'STRUCTURAL', 'LINE', 'DESIGN', 'PRODUCTION', name='editorialnotekind'), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('editorial_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_editorial_notes_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_editorial_notes_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_editorial_notes_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_editorial_notes_manuscript_id'), ['manuscript_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_editorial_notes_work_id'), ['work_id'], unique=False)

    op.create_table('manuscript_entity_links',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('TAGGED', 'FEATURES', 'REFERENCES', 'SET_IN', 'DERIVED_FROM', 'OTHER', name='manuscriptlinkrole'), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['knowledge_entities.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manuscript_entity_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manuscript_entity_links_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuscript_entity_links_manuscript_id'), ['manuscript_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuscript_entity_links_role'), ['role'], unique=False)

    op.create_table('production_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assignee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage', sa.Enum('LAYOUT', 'COVER_DESIGN', 'PREPRESS', 'PRINTING', name='productionstage'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'BLOCKED', 'DONE', name='productionitemstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_items_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_manuscript_id'), ['manuscript_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_work_id'), ['work_id'], unique=False)

    op.create_table('production_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('print_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('ebook_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('audiobook_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('cover_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('layout_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('prepress_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_records_audiobook_status'), ['audiobook_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_records_cover_status'), ['cover_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_records_ebook_status'), ['ebook_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_records_isbn'), ['isbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_records_layout_status'), ['layout_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_records_manuscript_id'), ['manuscript_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_production_records_prepress_status'), ['prepress_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_records_print_status'), ['print_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_records_release_date'), ['release_date'], unique=False)

    op.create_table('published_volumes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=False),
    sa.Column('public_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('music_track_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['music_track_id'], ['public_media_assets.id'], ),
    sa.ForeignKeyConstraint(['published_work_id'], ['published_works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('published_volumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_volumes_published_work_id'), ['published_work_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_volumes_volume_number'), ['volume_number'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verdict', sa.Enum('ACCEPT', 'REJECT', 'REVISE', 'HOLD', name='reviewverdict'), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('written_report', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('literary_quality_score', sa.Integer(), nullable=True),
    sa.Column('visual_potential_score', sa.Integer(), nullable=True),
    sa.Column('market_potential_score', sa.Integer(), nullable=True),
    sa.Column('originality_score', sa.Integer(), nullable=True),
    sa.Column('editorial_effort_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_manuscript_id'), ['manuscript_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_verdict'), ['verdict'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_work_id'), ['work_id'], unique=False)

    op.create_table('workflow_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'DEVELOPMENT_EDITING', 'COPY_EDITING', 'PROOFREADING', 'LAYOUT', 'COVER_DESIGN', 'PREPRESS', 'PUBLISHED', 'ARCHIVED', name='workflowstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'DEVELOPMENT_EDITING', 'COPY_EDITING', 'PROOFREADING', 'LAYOUT', 'COVER_DESIGN', 'PREPRESS', 'PUBLISHED', 'ARCHIVED', name='workflowstatus'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_manuscript_id'), ['manuscript_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_to_status'), ['to_status'], unique=False)

    op.create_table('published_chapters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_volume_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('public_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('music_track_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_intro_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['music_track_id'], ['public_media_assets.id'], ),
    sa.ForeignKeyConstraint(['published_volume_id'], ['published_volumes.id'], ),
    sa.ForeignKeyConstraint(['video_intro_id'], ['public_media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('published_chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_chapters_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_chapters_published_volume_id'), ['published_volume_id'], unique=False)

    op.create_table('published_pages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_chapter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('music_track_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_overlay_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['music_track_id'], ['public_media_assets.id'], ),
    sa.ForeignKeyConstraint(['published_chapter_id'], ['published_chapters.id'], ),
    sa.ForeignKeyConstraint(['video_overlay_id'], ['public_media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('published_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_pages_page_number'), ['page_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_pages_published_chapter_id'), ['published_chapter_id'], unique=False)

    op.create_table('public_hotspots',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'CHARACTER', 'LOCATION', 'LORE', 'EXTERNAL_LINK', 'AUDIO', 'VIDEO', name='hotspottype'), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.Column('audio_track_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['audio_track_id'], ['public_media_assets.id'], ),
    sa.ForeignKeyConstraint(['published_page_id'], ['published_pages.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['public_media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('public_hotspots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_hotspots_published_page_id'), ['published_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_hotspots_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_hotspots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_hotspots_type'))
        batch_op.drop_index(batch_op.f('ix_public_hotspots_published_page_id'))

    op.drop_table('public_hotspots')
    with op.batch_alter_table('published_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_pages_published_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_published_pages_page_number'))

    op.drop_table('published_pages')
    with op.batch_alter_table('published_chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_chapters_published_volume_id'))
        batch_op.drop_index(batch_op.f('ix_published_chapters_chapter_number'))

    op.drop_table('published_chapters')
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_events_to_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_manuscript_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_actor_id'))

    op.drop_table('workflow_events')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_work_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_verdict'))
        batch_op.drop_index(batch_op.f('ix_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_manuscript_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('published_volumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_volumes_volume_number'))
        batch_op.drop_index(batch_op.f('ix_published_volumes_published_work_id'))

    op.drop_table('published_volumes')
    with op.batch_alter_table('production_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_records_release_date'))
        batch_op.drop_index(batch_op.f('ix_production_records_print_status'))
        batch_op.drop_index(batch_op.f('ix_production_records_prepress_status'))
        batch_op.drop_index(batch_op.f('ix_production_records_manuscript_id'))
        batch_op.drop_index(batch_op.f('ix_production_records_layout_status'))
        batch_op.drop_index(batch_op.f('ix_production_records_isbn'))
        batch_op.drop_index(batch_op.f('ix_production_records_ebook_status'))
        batch_op.drop_index(batch_op.f('ix_production_records_cover_status'))
        batch_op.drop_index(batch_op.f('ix_production_records_audiobook_status'))

    op.drop_table('production_records')
    with op.batch_alter_table('production_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_items_work_id'))
        batch_op.drop_index(batch_op.f('ix_production_items_status'))
        batch_op.drop_index(batch_op.f('ix_production_items_stage'))
        batch_op.drop_index(batch_op.f('ix_production_items_manuscript_id'))
        batch_op.drop_index(batch_op.f('ix_production_items_due_date'))
        batch_op.drop_index(batch_op.f('ix_production_items_assignee_id'))

    op.drop_table('production_items')
    with op.batch_alter_table('manuscript_entity_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manuscript_entity_links_role'))
        batch_op.drop_index(batch_op.f('ix_manuscript_entity_links_manuscript_id'))
        batch_op.drop_index(batch_op.f('ix_manuscript_entity_links_entity_id'))

    op.drop_table('manuscript_entity_links')
    with op.batch_alter_table('editorial_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_editorial_notes_work_id'))
        batch_op.drop_index(batch_op.f('ix_editorial_notes_manuscript_id'))
        batch_op.drop_index(batch_op.f('ix_editorial_notes_kind'))
        batch_op.drop_index(batch_op.f('ix_editorial_notes_author_user_id'))
        batch_op.drop_index(batch_op.f('ix_editorial_notes_author_id'))

    op.drop_table('editorial_notes')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_work_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_status'))
        batch_op.drop_index(batch_op.f('ix_contracts_rights_territory'))
        batch_op.drop_index(batch_op.f('ix_contracts_manuscript_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_expiration_date'))
        batch_op.drop_index(batch_op.f('ix_contracts_author_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_uploader_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_manuscript_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_kind'))

    op.drop_table('attachments')
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_insights_manuscript_id'))
        batch_op.drop_index(batch_op.f('ix_ai_insights_feature'))

    op.drop_table('ai_insights')
    with op.batch_alter_table('rights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rights_work_id'))
        batch_op.drop_index(batch_op.f('ix_rights_territory'))
        batch_op.drop_index(batch_op.f('ix_rights_language'))
        batch_op.drop_index(batch_op.f('ix_rights_expiration_date'))

    op.drop_table('rights')
    with op.batch_alter_table('published_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_works_title'))
        batch_op.drop_index(batch_op.f('ix_published_works_status'))
        batch_op.drop_index(batch_op.f('ix_published_works_source_work_id'))
        batch_op.drop_index(batch_op.f('ix_published_works_slug'))
        batch_op.drop_index(batch_op.f('ix_published_works_publication_date'))

    op.drop_table('published_works')
    with op.batch_alter_table('manuscripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manuscripts_work_type'))
        batch_op.drop_index(batch_op.f('ix_manuscripts_work_id'))
        batch_op.drop_index(batch_op.f('ix_manuscripts_title'))
        batch_op.drop_index(batch_op.f('ix_manuscripts_submission_date'))
        batch_op.drop_index(batch_op.f('ix_manuscripts_status'))
        batch_op.drop_index(batch_op.f('ix_manuscripts_genre'))
        batch_op.drop_index(batch_op.f('ix_manuscripts_draft_status'))
        batch_op.drop_index(batch_op.f('ix_manuscripts_author_id'))

    op.drop_table('manuscripts')
    with op.batch_alter_table('graphic_novel_productions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graphic_novel_productions_work_id'))
        batch_op.drop_index(batch_op.f('ix_graphic_novel_productions_script_status'))

    op.drop_table('graphic_novel_productions')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_work_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_status'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_date'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_works_work_type'))
        batch_op.drop_index(batch_op.f('ix_works_title'))
        batch_op.drop_index(batch_op.f('ix_works_status'))
        batch_op.drop_index(batch_op.f('ix_works_genre'))
        batch_op.drop_index(batch_op.f('ix_works_author_id'))

    op.drop_table('works')
    with op.batch_alter_table('knowledge_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_relationships_target_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_relationships_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_relationships_kind'))

    op.drop_table('knowledge_relationships')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('public_media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_media_assets_type'))
        batch_op.drop_index(batch_op.f('ix_public_media_assets_public_visibility'))

    op.drop_table('public_media_assets')
    with op.batch_alter_table('knowledge_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_entities_slug'))
        batch_op.drop_index(batch_op.f('ix_knowledge_entities_name'))
        batch_op.drop_index(batch_op.f('ix_knowledge_entities_kind'))

    op.drop_table('knowledge_entities')
    with op.batch_alter_table('integration_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_points_type'))
        batch_op.drop_index(batch_op.f('ix_integration_points_status'))
        batch_op.drop_index(batch_op.f('ix_integration_points_name'))

    op.drop_table('integration_points')
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_pen_name'))
        batch_op.drop_index(batch_op.f('ix_authors_full_name'))
        batch_op.drop_index(batch_op.f('ix_authors_email'))

    op.drop_table('authors')
    # ### end Alembic commands ###
