"""transmedia: story worlds, series, adaptation dossiers

Revision ID: 0002_transmedia
Revises: 0001_baseline
Create Date: 2026-06-25 09:22:15.830966
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0002_transmedia'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_worlds',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canon_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('DEVELOPING', 'ACTIVE', 'DORMANT', 'ARCHIVED', name='storyworldstatus'), nullable=False),
    sa.Column('visual_identity_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['story_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_worlds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_worlds_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_worlds_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_worlds_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_worlds_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_story_worlds_status'), ['status'], unique=False)

    op.create_table('story_series',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ONGOING', 'COMPLETE', 'ON_HOLD', 'ARCHIVED', name='storyseriesstatus'), nullable=False),
    sa.ForeignKeyConstraint(['story_world_id'], ['story_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_series_sequence_order'), ['sequence_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_series_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_series_story_world_id'), ['story_world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_series_title'), ['title'], unique=False)

    op.create_table('adaptation_dossiers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_medium', sa.Enum('BOOK', 'GRAPHIC_NOVEL', 'FILM', 'SHORT_FILM', 'SERIES', 'ANIMATION', 'AUDIO_DRAMA', 'WEB_EXPERIENCE', 'GAME', 'OTHER', name='medium'), nullable=False),
    sa.Column('target_division', sa.Enum('PUBLISHING', 'PICTURES', 'INTERACTIVE', 'AUDIO', 'CROSS_MEDIA', name='studiodivision'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'OPTIONED', 'IN_DEVELOPMENT', 'IN_PRODUCTION', 'RELEASED', 'ON_HOLD', 'ABANDONED', name='adaptationstatus'), nullable=False),
    sa.Column('logline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('intended_scope', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('rights_clearance', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'CLEARED', 'BLOCKED', 'NOT_REQUIRED', name='rightsclearancestate'), nullable=False),
    sa.Column('creative_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_revision', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.ForeignKeyConstraint(['source_work_id'], ['works.id'], ),
    sa.ForeignKeyConstraint(['target_work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adaptation_dossiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adaptation_dossiers_rights_clearance'), ['rights_clearance'], unique=False)
        batch_op.create_index(batch_op.f('ix_adaptation_dossiers_source_work_id'), ['source_work_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adaptation_dossiers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_adaptation_dossiers_target_division'), ['target_division'], unique=False)
        batch_op.create_index(batch_op.f('ix_adaptation_dossiers_target_medium'), ['target_medium'], unique=False)
        batch_op.create_index(batch_op.f('ix_adaptation_dossiers_target_work_id'), ['target_work_id'], unique=False)

    # Extend ``works`` with plain ADD COLUMN + CREATE INDEX (no table rebuild),
    # which is portable and avoids SQLite batch recreation reflecting the
    # baseline's unnamed author FK. The two non-null enum columns carry a
    # server_default so the migration is safe on a populated table; fresh
    # create_all databases enforce the FK relationships at the model level.
    op.add_column('works', sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('works', sa.Column('story_series_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('works', sa.Column('series_order', sa.Integer(), nullable=True))
    op.add_column('works', sa.Column('primary_division', sa.Enum('PUBLISHING', 'PICTURES', 'INTERACTIVE', 'AUDIO', 'CROSS_MEDIA', name='studiodivision'), nullable=False, server_default='PUBLISHING'))
    op.add_column('works', sa.Column('primary_medium', sa.Enum('BOOK', 'GRAPHIC_NOVEL', 'FILM', 'SHORT_FILM', 'SERIES', 'ANIMATION', 'AUDIO_DRAMA', 'WEB_EXPERIENCE', 'GAME', 'OTHER', name='medium'), nullable=True))
    op.add_column('works', sa.Column('canon_status', sa.Enum('CANON', 'SOFT_CANON', 'ALTERNATE', 'NON_CANON', 'UNDECIDED', name='canonstate'), nullable=False, server_default='CANON'))
    op.add_column('works', sa.Column('source_work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_works_canon_status'), 'works', ['canon_status'], unique=False)
    op.create_index(op.f('ix_works_primary_division'), 'works', ['primary_division'], unique=False)
    op.create_index(op.f('ix_works_primary_medium'), 'works', ['primary_medium'], unique=False)
    op.create_index(op.f('ix_works_source_work_id'), 'works', ['source_work_id'], unique=False)
    op.create_index(op.f('ix_works_story_series_id'), 'works', ['story_series_id'], unique=False)
    op.create_index(op.f('ix_works_story_world_id'), 'works', ['story_world_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_story_world_id'), table_name='works')
    op.drop_index(op.f('ix_works_story_series_id'), table_name='works')
    op.drop_index(op.f('ix_works_source_work_id'), table_name='works')
    op.drop_index(op.f('ix_works_primary_medium'), table_name='works')
    op.drop_index(op.f('ix_works_primary_division'), table_name='works')
    op.drop_index(op.f('ix_works_canon_status'), table_name='works')
    op.drop_column('works', 'source_work_id')
    op.drop_column('works', 'canon_status')
    op.drop_column('works', 'primary_medium')
    op.drop_column('works', 'primary_division')
    op.drop_column('works', 'series_order')
    op.drop_column('works', 'story_series_id')
    op.drop_column('works', 'story_world_id')

    with op.batch_alter_table('adaptation_dossiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adaptation_dossiers_target_work_id'))
        batch_op.drop_index(batch_op.f('ix_adaptation_dossiers_target_medium'))
        batch_op.drop_index(batch_op.f('ix_adaptation_dossiers_target_division'))
        batch_op.drop_index(batch_op.f('ix_adaptation_dossiers_status'))
        batch_op.drop_index(batch_op.f('ix_adaptation_dossiers_source_work_id'))
        batch_op.drop_index(batch_op.f('ix_adaptation_dossiers_rights_clearance'))

    op.drop_table('adaptation_dossiers')
    with op.batch_alter_table('story_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_series_title'))
        batch_op.drop_index(batch_op.f('ix_story_series_story_world_id'))
        batch_op.drop_index(batch_op.f('ix_story_series_status'))
        batch_op.drop_index(batch_op.f('ix_story_series_sequence_order'))

    op.drop_table('story_series')
    with op.batch_alter_table('story_worlds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_worlds_status'))
        batch_op.drop_index(batch_op.f('ix_story_worlds_slug'))
        batch_op.drop_index(batch_op.f('ix_story_worlds_parent_id'))
        batch_op.drop_index(batch_op.f('ix_story_worlds_owner_id'))
        batch_op.drop_index(batch_op.f('ix_story_worlds_name'))

    op.drop_table('story_worlds')
    # ### end Alembic commands ###
