"""collaboration project memberships and audits

Revision ID: 0003_collaboration
Revises: 0002_transmedia
Create Date: 2026-06-25 10:05:20.505228
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0003_collaboration'
down_revision: Union[str, None] = '0002_transmedia'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_audits',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('membership_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sa.Enum('INVITED', 'ACCEPTED', 'DECLINED', 'ROLE_CHANGED', 'SUSPENDED', 'REACTIVATED', 'REVOKED', name='membershipauditaction'), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'DIRECTOR', 'EDITOR', 'WRITER', 'ARTIST', 'LETTERER', 'COLOURIST', 'ANIMATOR', 'SOUND_DESIGNER', 'TECHNICIAN', 'PRODUCTION_MANAGER', 'MARKETING', 'REVIEWER', 'VIEWER', name='projectrole'), nullable=True),
    sa.Column('from_status', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'DECLINED', 'REVOKED', name='membershipstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'DECLINED', 'REVOKED', name='membershipstatus'), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('membership_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_audits_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_audits_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_audits_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_audits_story_world_id'), ['story_world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_audits_subject_user_id'), ['subject_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_audits_work_id'), ['work_id'], unique=False)

    op.create_table('project_memberships',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'DIRECTOR', 'EDITOR', 'WRITER', 'ARTIST', 'LETTERER', 'COLOURIST', 'ANIMATOR', 'SOUND_DESIGNER', 'TECHNICIAN', 'PRODUCTION_MANAGER', 'MARKETING', 'REVIEWER', 'VIEWER', name='projectrole'), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'DECLINED', 'REVOKED', name='membershipstatus'), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story_world_id'], ['story_worlds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_memberships_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_memberships_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_memberships_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_memberships_story_world_id'), ['story_world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_memberships_work_id'), ['work_id'], unique=False)

    # NOTE: Alembic also detects "missing" foreign keys on ``works`` for
    # source_work_id / story_series_id / story_world_id. Those columns were
    # deliberately added in 0002 as plain columns (no FK constraint) to avoid a
    # SQLite batch table rebuild; the relationships are enforced at the model
    # layer. We intentionally do NOT add those constraints here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_memberships_work_id'))
        batch_op.drop_index(batch_op.f('ix_project_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_memberships_story_world_id'))
        batch_op.drop_index(batch_op.f('ix_project_memberships_status'))
        batch_op.drop_index(batch_op.f('ix_project_memberships_role'))
        batch_op.drop_index(batch_op.f('ix_project_memberships_created_by_id'))

    op.drop_table('project_memberships')
    with op.batch_alter_table('membership_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_audits_work_id'))
        batch_op.drop_index(batch_op.f('ix_membership_audits_subject_user_id'))
        batch_op.drop_index(batch_op.f('ix_membership_audits_story_world_id'))
        batch_op.drop_index(batch_op.f('ix_membership_audits_membership_id'))
        batch_op.drop_index(batch_op.f('ix_membership_audits_actor_id'))
        batch_op.drop_index(batch_op.f('ix_membership_audits_action'))

    op.drop_table('membership_audits')
    # ### end Alembic commands ###
