"""production task system

Revision ID: 0004_production_tasks
Revises: 0003_collaboration
Create Date: 2026-06-25 11:00:26.836116
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0004_production_tasks'
down_revision: Union[str, None] = '0003_collaboration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Altering production_items forces a SQLite table rebuild, which reflects the
# baseline's *unnamed* foreign keys. Supplying a naming convention lets the
# batch operation name them on the way through (otherwise: "constraint must
# have a name"). Same fix used for the works table in 0002.
NAMING = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_activities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('CREATED', 'UPDATED', 'STATUS_CHANGED', 'ASSIGNED', 'REASSIGNED', 'BLOCKED', 'UNBLOCKED', 'DEPENDENCY_ADDED', 'DEPENDENCY_REMOVED', 'APPROVAL_REQUESTED', 'APPROVAL_DECIDED', 'MILESTONE_LINKED', 'COMMENTED', 'COMPLETED', 'REOPENED', 'TEMPLATE_APPLIED', name='productionactivitytype'), nullable=False),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('from_status', sa.Enum('PENDING', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'TODO', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'CANCELLED', name='productionitemstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'TODO', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'CANCELLED', name='productionitemstatus'), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_activities_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_activities_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_activities_type'), ['type'], unique=False)

    op.create_table('production_milestones',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('division', sa.Enum('PUBLISHING', 'PICTURES', 'INTERACTIVE', 'AUDIO', 'CROSS_MEDIA', name='studiodivision'), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'REACHED', 'MISSED', 'CANCELLED', name='milestonestatus'), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('reached_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['story_world_id'], ['story_worlds.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_milestones_division'), ['division'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_milestones_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_milestones_story_world_id'), ['story_world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_milestones_target_date'), ['target_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_milestones_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_milestones_work_id'), ['work_id'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('requested_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approver_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'CANCELLED', name='approvalstatus'), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='approvaldecision'), nullable=True),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['production_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_requested_by_id'), ['requested_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_task_id'), ['task_id'], unique=False)

    op.create_table('production_dependencies',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('depends_on_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('FINISH_TO_START', 'START_TO_START', 'RELATED', name='dependencytype'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_id'], ['production_items.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['production_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_dependencies_depends_on_id'), ['depends_on_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_dependencies_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_dependencies_type'), ['type'], unique=False)

    with op.batch_alter_table(
        'production_items', schema=None, naming_convention=NAMING
    ) as batch_op:
        batch_op.add_column(sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('division', sa.Enum('PUBLISHING', 'PICTURES', 'INTERACTIVE', 'AUDIO', 'CROSS_MEDIA', name='studiodivision'), nullable=True))
        batch_op.add_column(sa.Column('track', sa.Enum('EDITORIAL', 'ART', 'LETTERING', 'COLOR', 'LAYOUT', 'PREPRESS', 'PRINT', 'SCRIPT', 'STORYBOARD', 'ANIMATION', 'VFX', 'PHOTOGRAPHY', 'EDITING', 'SOUND', 'MUSIC', 'ENGINEERING', 'DESIGN', 'QA', 'MARKETING', 'PRODUCTION', 'OTHER', name='productiontrack'), nullable=True))
        # New NOT NULL enum/int columns carry a server_default so the rebuild is
        # safe on a populated table (existing rows are pre-task-system items).
        batch_op.add_column(sa.Column('task_type', sa.Enum('TASK', 'REVIEW', 'DELIVERABLE', 'APPROVAL', 'BUG', 'RESEARCH', 'ADMIN', name='productiontasktype'), nullable=False, server_default='TASK'))
        batch_op.add_column(sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='productionpriority'), nullable=False, server_default='MEDIUM'))
        batch_op.add_column(sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('milestone_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('completed_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('estimated_effort', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_effort', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('blocked_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('acceptance_criteria', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('deliverable_asset', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
        batch_op.add_column(sa.Column('revision_number', sa.Integer(), nullable=False, server_default='0'))
        batch_op.alter_column('manuscript_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'TODO', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'CANCELLED', name='productionitemstatus'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_production_items_completed_date'), ['completed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_division'), ['division'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_story_world_id'), ['story_world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_items_track'), ['track'], unique=False)
        batch_op.create_foreign_key('fk_production_items_milestone_id_production_milestones', 'production_milestones', ['milestone_id'], ['id'])
        batch_op.create_foreign_key('fk_production_items_story_world_id_story_worlds', 'story_worlds', ['story_world_id'], ['id'])
        batch_op.create_foreign_key('fk_production_items_parent_id_production_items', 'production_items', ['parent_id'], ['id'])
        batch_op.create_foreign_key('fk_production_items_creator_id_users', 'users', ['creator_id'], ['id'])
        batch_op.create_foreign_key('fk_production_items_reviewer_id_users', 'users', ['reviewer_id'], ['id'])

    # NOTE: Alembic also reports "missing" foreign keys on the works table
    # (story_world_id / story_series_id / source_work_id). Those columns were
    # deliberately added in 0002 without FK constraints (to avoid a SQLite
    # rebuild); the relationships are enforced at the model layer. We do not add
    # them here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The dropped columns carry the new foreign keys; the batch rebuild removes
    # them with the columns, so no explicit drop_constraint is needed.
    with op.batch_alter_table(
        'production_items', schema=None, naming_convention=NAMING
    ) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_items_track'))
        batch_op.drop_index(batch_op.f('ix_production_items_title'))
        batch_op.drop_index(batch_op.f('ix_production_items_task_type'))
        batch_op.drop_index(batch_op.f('ix_production_items_story_world_id'))
        batch_op.drop_index(batch_op.f('ix_production_items_start_date'))
        batch_op.drop_index(batch_op.f('ix_production_items_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_production_items_priority'))
        batch_op.drop_index(batch_op.f('ix_production_items_parent_id'))
        batch_op.drop_index(batch_op.f('ix_production_items_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_production_items_division'))
        batch_op.drop_index(batch_op.f('ix_production_items_creator_id'))
        batch_op.drop_index(batch_op.f('ix_production_items_completed_date'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'TODO', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'CANCELLED', name='productionitemstatus'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('manuscript_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('revision_number')
        batch_op.drop_column('deliverable_asset')
        batch_op.drop_column('acceptance_criteria')
        batch_op.drop_column('blocked_reason')
        batch_op.drop_column('actual_effort')
        batch_op.drop_column('estimated_effort')
        batch_op.drop_column('completed_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('milestone_id')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('reviewer_id')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('priority')
        batch_op.drop_column('task_type')
        batch_op.drop_column('track')
        batch_op.drop_column('division')
        batch_op.drop_column('story_world_id')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('production_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_dependencies_type'))
        batch_op.drop_index(batch_op.f('ix_production_dependencies_task_id'))
        batch_op.drop_index(batch_op.f('ix_production_dependencies_depends_on_id'))

    op.drop_table('production_dependencies')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_task_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_target_type'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_target_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_approver_id'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('production_milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_milestones_work_id'))
        batch_op.drop_index(batch_op.f('ix_production_milestones_title'))
        batch_op.drop_index(batch_op.f('ix_production_milestones_target_date'))
        batch_op.drop_index(batch_op.f('ix_production_milestones_story_world_id'))
        batch_op.drop_index(batch_op.f('ix_production_milestones_status'))
        batch_op.drop_index(batch_op.f('ix_production_milestones_division'))

    op.drop_table('production_milestones')
    with op.batch_alter_table('production_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_activities_type'))
        batch_op.drop_index(batch_op.f('ix_production_activities_task_id'))
        batch_op.drop_index(batch_op.f('ix_production_activities_actor_id'))

    op.drop_table('production_activities')
    # ### end Alembic commands ###
