"""asset library

Revision ID: 0005_asset_library
Revises: 0004_production_tasks
Create Date: 2026-06-25 11:28:01.944295
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0005_asset_library'
down_revision: Union[str, None] = '0004_production_tasks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('asset_type', sa.Enum('IMAGE', 'ILLUSTRATION', 'CHARACTER_DESIGN', 'ENVIRONMENT_DESIGN', 'COVER', 'PAGE_ART', 'STORYBOARD', 'CONCEPT_ART', 'AUDIO', 'MUSIC', 'SOUND_EFFECT', 'VOICE', 'VIDEO', 'ANIMATION', 'MODEL_3D', 'TEXTURE', 'FONT', 'SCRIPT', 'DOCUMENT', 'OTHER', name='assettype'), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canon_status', sa.Enum('CANON', 'SOFT_CANON', 'ALTERNATE', 'NON_CANON', 'UNDECIDED', name='canonstate'), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'INTERNAL', 'RESTRICTED', 'PUBLIC_CANDIDATE', name='assetvisibility'), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story_world_id'], ['story_worlds.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_canon_status'), ['canon_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_current_version_id'), ['current_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_story_world_id'), ['story_world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_visibility'), ['visibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_work_id'), ['work_id'], unique=False)

    op.create_table('asset_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approval_status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='assetapprovalstatus'), nullable=False),
    sa.Column('superseded_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('technical_metadata', sa.JSON(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['asset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_versions_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_versions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_versions_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_versions_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_versions_superseded_by_id'), ['superseded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_versions_version_number'), ['version_number'], unique=False)

    op.create_table('licence_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rights_holder', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('licence_type', sa.Enum('PROPRIETARY', 'COMMISSIONED', 'WORK_FOR_HIRE', 'STOCK', 'CREATIVE_COMMONS', 'PUBLIC_DOMAIN', 'ROYALTY_FREE', 'RIGHTS_MANAGED', 'AI_GENERATED', 'OTHER', name='licencetype'), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('territory', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('permitted_uses', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attribution_requirements', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('evidence_storage_key', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('review_state', sa.Enum('NOT_REVIEWED', 'PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='licencereviewstate'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('licence_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licence_records_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_licence_records_expiration_date'), ['expiration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_licence_records_licence_type'), ['licence_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_licence_records_review_state'), ['review_state'], unique=False)

    op.create_table('asset_links',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_type', sa.Enum('CHARACTER', 'LOCATION', 'KNOWLEDGE_ENTITY', 'PAGE', 'PANEL', 'SCENE', 'SHOT', 'PRODUCTION_TASK', 'PUBLIC_READER_RECORD', 'WORK', 'STORY_WORLD', 'OTHER', name='assetlinktargettype'), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_links_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_links_asset_version_id'), ['asset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_links_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_links_target_type'), ['target_type'], unique=False)

    op.create_table('provenance_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('asset_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('HUMAN_CREATED', 'AI_ASSISTED', 'AI_GENERATED', 'MIXED', name='provenancekind'), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('base_model', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('base_model_version', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('adapter_identifiers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('negative_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('sampler', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('source_references', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('controlnet_inputs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generating_workflow', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('human_modifications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation_date', sa.DateTime(), nullable=True),
    sa.Column('responsible_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('commercial_use_review', sa.Enum('NOT_REVIEWED', 'UNDER_REVIEW', 'CLEARED', 'RESTRICTED', 'BLOCKED', name='commercialusereviewstatus'), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provenance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provenance_records_asset_version_id'), ['asset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provenance_records_commercial_use_review'), ['commercial_use_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_provenance_records_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_provenance_records_responsible_user_id'), ['responsible_user_id'], unique=False)

    # NOTE: Alembic reports "missing" foreign keys on the works table
    # (story_world_id / story_series_id / source_work_id). Those columns were
    # deliberately added in 0002 without FK constraints; the relationships are
    # enforced at the model layer. We do not add them here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provenance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provenance_records_responsible_user_id'))
        batch_op.drop_index(batch_op.f('ix_provenance_records_kind'))
        batch_op.drop_index(batch_op.f('ix_provenance_records_commercial_use_review'))
        batch_op.drop_index(batch_op.f('ix_provenance_records_asset_version_id'))

    op.drop_table('provenance_records')
    with op.batch_alter_table('asset_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_links_target_type'))
        batch_op.drop_index(batch_op.f('ix_asset_links_target_id'))
        batch_op.drop_index(batch_op.f('ix_asset_links_asset_version_id'))
        batch_op.drop_index(batch_op.f('ix_asset_links_asset_id'))

    op.drop_table('asset_links')
    with op.batch_alter_table('licence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licence_records_review_state'))
        batch_op.drop_index(batch_op.f('ix_licence_records_licence_type'))
        batch_op.drop_index(batch_op.f('ix_licence_records_expiration_date'))
        batch_op.drop_index(batch_op.f('ix_licence_records_asset_id'))

    op.drop_table('licence_records')
    with op.batch_alter_table('asset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_versions_version_number'))
        batch_op.drop_index(batch_op.f('ix_asset_versions_superseded_by_id'))
        batch_op.drop_index(batch_op.f('ix_asset_versions_creator_id'))
        batch_op.drop_index(batch_op.f('ix_asset_versions_checksum'))
        batch_op.drop_index(batch_op.f('ix_asset_versions_asset_id'))
        batch_op.drop_index(batch_op.f('ix_asset_versions_approval_status'))

    op.drop_table('asset_versions')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_work_id'))
        batch_op.drop_index(batch_op.f('ix_assets_visibility'))
        batch_op.drop_index(batch_op.f('ix_assets_title'))
        batch_op.drop_index(batch_op.f('ix_assets_story_world_id'))
        batch_op.drop_index(batch_op.f('ix_assets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_assets_current_version_id'))
        batch_op.drop_index(batch_op.f('ix_assets_canon_status'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))

    op.drop_table('assets')
    # ### end Alembic commands ###
