"""graphic novel hierarchy

Revision ID: 0006_gn_hierarchy
Revises: 0005_asset_library
Create Date: 2026-06-25 11:54:20.319406
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0006_gn_hierarchy'
down_revision: Union[str, None] = '0005_asset_library'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gn_volumes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('production_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('synopsis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETE', 'ON_HOLD', name='gnstatus'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['graphic_novel_productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gn_volumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gn_volumes_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_volumes_production_id'), ['production_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_volumes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_volumes_volume_number'), ['volume_number'], unique=False)

    op.create_table('gn_chapters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('volume_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('synopsis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETE', 'ON_HOLD', name='gnstatus'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['volume_id'], ['gn_volumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gn_chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gn_chapters_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_chapters_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_chapters_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_chapters_volume_id'), ['volume_id'], unique=False)

    op.create_table('gn_sequences',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('chapter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETE', 'ON_HOLD', name='gnstatus'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['gn_chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gn_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gn_sequences_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_sequences_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_sequences_sequence_number'), ['sequence_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_sequences_status'), ['status'], unique=False)

    op.create_table('gn_pages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sequence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETE', 'ON_HOLD', name='gnstatus'), nullable=False),
    sa.Column('spread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_side', sa.Enum('LEFT', 'RIGHT', 'SINGLE', name='pageside'), nullable=False),
    sa.Column('script', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_brief', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dialogue_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lettering_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('colour_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('final_status', sa.Enum('NOT_PLANNED', 'PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='streamstatus'), nullable=False),
    sa.Column('print_width_mm', sa.Float(), nullable=True),
    sa.Column('print_height_mm', sa.Float(), nullable=True),
    sa.Column('bleed_mm', sa.Float(), nullable=True),
    sa.Column('safe_area_mm', sa.Float(), nullable=True),
    sa.Column('master_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('curation_status', sa.Enum('NOT_READY', 'READY_FOR_CURATION', 'IN_CURATION', 'HANDED_OFF', name='curationstatus'), nullable=False),
    sa.Column('published_page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['master_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['published_page_id'], ['published_pages.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['gn_sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gn_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gn_pages_curation_status'), ['curation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_pages_final_status'), ['final_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_pages_master_asset_id'), ['master_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_pages_page_number'), ['page_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_pages_page_side'), ['page_side'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_pages_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_pages_published_page_id'), ['published_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_pages_sequence_id'), ['sequence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_pages_spread_id'), ['spread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_pages_status'), ['status'], unique=False)

    op.create_table('gn_page_entity_links',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['knowledge_entities.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['gn_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gn_page_entity_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gn_page_entity_links_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_page_entity_links_page_id'), ['page_id'], unique=False)

    op.create_table('gn_panels',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('panel_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETE', 'ON_HOLD', name='gnstatus'), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('script_beat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dialogue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('captions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sound_effects', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('camera_framing', sa.Enum('ESTABLISHING', 'EXTREME_WIDE', 'WIDE', 'FULL', 'MEDIUM', 'MEDIUM_CLOSE', 'CLOSE_UP', 'EXTREME_CLOSE_UP', 'INSERT', 'OTHER', name='cameraframing'), nullable=True),
    sa.Column('camera_angle', sa.Enum('EYE_LEVEL', 'HIGH', 'LOW', 'BIRDS_EYE', 'WORMS_EYE', 'DUTCH', 'OVER_SHOULDER', 'POV', 'OTHER', name='cameraangle'), nullable=True),
    sa.Column('lens_metadata', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('continuity_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('storyboard_asset_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('final_asset_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approval_status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='assetapprovalstatus'), nullable=False),
    sa.ForeignKeyConstraint(['final_asset_version_id'], ['asset_versions.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['gn_pages.id'], ),
    sa.ForeignKeyConstraint(['storyboard_asset_version_id'], ['asset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gn_panels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gn_panels_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panels_camera_angle'), ['camera_angle'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panels_camera_framing'), ['camera_framing'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panels_final_asset_version_id'), ['final_asset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panels_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panels_panel_number'), ['panel_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panels_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panels_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panels_storyboard_asset_version_id'), ['storyboard_asset_version_id'], unique=False)

    op.create_table('gn_panel_elements',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('panel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('element_type', sa.Enum('CHARACTER', 'PROP', 'LOCATION', 'TEXT', name='panelelementtype'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['knowledge_entities.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['gn_panels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gn_panel_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gn_panel_elements_asset_version_id'), ['asset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panel_elements_element_type'), ['element_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panel_elements_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panel_elements_panel_id'), ['panel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gn_panel_elements_position'), ['position'], unique=False)

    # NOTE: works story_world_id / story_series_id / source_work_id were added
    # in 0002 deliberately without FK constraints (model-layer only). We do not
    # add them here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gn_panel_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gn_panel_elements_position'))
        batch_op.drop_index(batch_op.f('ix_gn_panel_elements_panel_id'))
        batch_op.drop_index(batch_op.f('ix_gn_panel_elements_entity_id'))
        batch_op.drop_index(batch_op.f('ix_gn_panel_elements_element_type'))
        batch_op.drop_index(batch_op.f('ix_gn_panel_elements_asset_version_id'))

    op.drop_table('gn_panel_elements')
    with op.batch_alter_table('gn_panels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gn_panels_storyboard_asset_version_id'))
        batch_op.drop_index(batch_op.f('ix_gn_panels_status'))
        batch_op.drop_index(batch_op.f('ix_gn_panels_position'))
        batch_op.drop_index(batch_op.f('ix_gn_panels_panel_number'))
        batch_op.drop_index(batch_op.f('ix_gn_panels_page_id'))
        batch_op.drop_index(batch_op.f('ix_gn_panels_final_asset_version_id'))
        batch_op.drop_index(batch_op.f('ix_gn_panels_camera_framing'))
        batch_op.drop_index(batch_op.f('ix_gn_panels_camera_angle'))
        batch_op.drop_index(batch_op.f('ix_gn_panels_approval_status'))

    op.drop_table('gn_panels')
    with op.batch_alter_table('gn_page_entity_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gn_page_entity_links_page_id'))
        batch_op.drop_index(batch_op.f('ix_gn_page_entity_links_entity_id'))

    op.drop_table('gn_page_entity_links')
    with op.batch_alter_table('gn_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gn_pages_status'))
        batch_op.drop_index(batch_op.f('ix_gn_pages_spread_id'))
        batch_op.drop_index(batch_op.f('ix_gn_pages_sequence_id'))
        batch_op.drop_index(batch_op.f('ix_gn_pages_published_page_id'))
        batch_op.drop_index(batch_op.f('ix_gn_pages_position'))
        batch_op.drop_index(batch_op.f('ix_gn_pages_page_side'))
        batch_op.drop_index(batch_op.f('ix_gn_pages_page_number'))
        batch_op.drop_index(batch_op.f('ix_gn_pages_master_asset_id'))
        batch_op.drop_index(batch_op.f('ix_gn_pages_final_status'))
        batch_op.drop_index(batch_op.f('ix_gn_pages_curation_status'))

    op.drop_table('gn_pages')
    with op.batch_alter_table('gn_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gn_sequences_status'))
        batch_op.drop_index(batch_op.f('ix_gn_sequences_sequence_number'))
        batch_op.drop_index(batch_op.f('ix_gn_sequences_position'))
        batch_op.drop_index(batch_op.f('ix_gn_sequences_chapter_id'))

    op.drop_table('gn_sequences')
    with op.batch_alter_table('gn_chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gn_chapters_volume_id'))
        batch_op.drop_index(batch_op.f('ix_gn_chapters_status'))
        batch_op.drop_index(batch_op.f('ix_gn_chapters_position'))
        batch_op.drop_index(batch_op.f('ix_gn_chapters_chapter_number'))

    op.drop_table('gn_chapters')
    with op.batch_alter_table('gn_volumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gn_volumes_volume_number'))
        batch_op.drop_index(batch_op.f('ix_gn_volumes_status'))
        batch_op.drop_index(batch_op.f('ix_gn_volumes_production_id'))
        batch_op.drop_index(batch_op.f('ix_gn_volumes_position'))

    op.drop_table('gn_volumes')
    # ### end Alembic commands ###
