"""screen pictures

Revision ID: 0007_screen
Revises: 0006_gn_hierarchy
Create Date: 2026-06-25 12:23:53.643913
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0007_screen'
down_revision: Union[str, None] = '0006_gn_hierarchy'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screen_projects',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dossier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('format', sa.Enum('FILM', 'SHORT', 'SERIES', 'ANIMATION', name='screenformat'), nullable=False),
    sa.Column('status', sa.Enum('DEVELOPMENT', 'PRE_PRODUCTION', 'PRODUCTION', 'POST_PRODUCTION', 'DELIVERED', 'ON_HOLD', 'CANCELLED', name='screenprojectstatus'), nullable=False),
    sa.Column('logline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('synopsis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['adaptation_dossiers.id'], ),
    sa.ForeignKeyConstraint(['source_work_id'], ['works.id'], ),
    sa.ForeignKeyConstraint(['story_world_id'], ['story_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screen_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_projects_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_projects_format'), ['format'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_projects_source_work_id'), ['source_work_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_projects_story_world_id'), ['story_world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_projects_title'), ['title'], unique=False)

    op.create_table('screen_units',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('screen_project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_type', sa.Enum('EPISODE', 'REEL', 'ACT', 'PART', name='screenunittype'), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('synopsis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETE', 'ON_HOLD', name='screenstatus'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['screen_project_id'], ['screen_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screen_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_units_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_units_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_units_screen_project_id'), ['screen_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_units_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_units_unit_type'), ['unit_type'], unique=False)

    op.create_table('screen_sequences',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('unit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETE', 'ON_HOLD', name='screenstatus'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['screen_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screen_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_sequences_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_sequences_sequence_number'), ['sequence_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_sequences_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_sequences_unit_id'), ['unit_id'], unique=False)

    op.create_table('screen_scenes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sequence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('heading', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('environment', sa.Enum('INT', 'EXT', 'INT_EXT', name='sceneenvironment'), nullable=False),
    sa.Column('time_of_day', sa.Enum('DAY', 'NIGHT', 'DAWN', 'DUSK', 'MORNING', 'EVENING', 'CONTINUOUS', 'LATER', 'UNSPECIFIED', name='scenetimeofday'), nullable=False),
    sa.Column('synopsis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('script_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_duration_seconds', sa.Float(), nullable=True),
    sa.Column('production_status', sa.Enum('PLANNED', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETE', 'ON_HOLD', name='screenstatus'), nullable=False),
    sa.Column('continuity_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['screen_sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screen_scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_scenes_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_scenes_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_scenes_production_status'), ['production_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_scenes_scene_number'), ['scene_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_scenes_sequence_id'), ['sequence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_scenes_time_of_day'), ['time_of_day'], unique=False)

    op.create_table('screen_scene_characters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('scene_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['knowledge_entities.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['screen_scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screen_scene_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_scene_characters_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_scene_characters_scene_id'), ['scene_id'], unique=False)

    op.create_table('screen_shots',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('scene_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('framing', sa.Enum('ESTABLISHING', 'EXTREME_WIDE', 'WIDE', 'FULL', 'MEDIUM', 'MEDIUM_CLOSE', 'CLOSE_UP', 'EXTREME_CLOSE_UP', 'INSERT', 'OTHER', name='cameraframing'), nullable=True),
    sa.Column('camera_angle', sa.Enum('EYE_LEVEL', 'HIGH', 'LOW', 'BIRDS_EYE', 'WORMS_EYE', 'DUTCH', 'OVER_SHOULDER', 'POV', 'OTHER', name='cameraangle'), nullable=True),
    sa.Column('movement', sa.Enum('STATIC', 'PAN', 'TILT', 'DOLLY', 'TRACK', 'ZOOM', 'CRANE', 'HANDHELD', 'STEADICAM', 'AERIAL', 'OTHER', name='shotmovement'), nullable=True),
    sa.Column('lens', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('blocking', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lighting', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dialogue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sound', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('music', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vfx', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_storyboard_panel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETE', 'ON_HOLD', name='screenstatus'), nullable=False),
    sa.Column('approval', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='assetapprovalstatus'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['screen_scenes.id'], ),
    sa.ForeignKeyConstraint(['source_storyboard_panel_id'], ['gn_panels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screen_shots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_shots_approval'), ['approval'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_shots_camera_angle'), ['camera_angle'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_shots_framing'), ['framing'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_shots_movement'), ['movement'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_shots_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_shots_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_shots_shot_number'), ['shot_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_shots_source_storyboard_panel_id'), ['source_storyboard_panel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_shots_status'), ['status'], unique=False)

    op.create_table('screen_shot_assets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('shot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['screen_shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screen_shot_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_shot_assets_asset_version_id'), ['asset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_shot_assets_shot_id'), ['shot_id'], unique=False)

    op.create_table('screen_shot_panels',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('shot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('panel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['gn_panels.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['screen_shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screen_shot_panels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_shot_panels_panel_id'), ['panel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_shot_panels_shot_id'), ['shot_id'], unique=False)

    # NOTE: works story_world_id / story_series_id / source_work_id were added
    # in 0002 deliberately without FK constraints (model-layer only). We do not
    # add them here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen_shot_panels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_shot_panels_shot_id'))
        batch_op.drop_index(batch_op.f('ix_screen_shot_panels_panel_id'))

    op.drop_table('screen_shot_panels')
    with op.batch_alter_table('screen_shot_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_shot_assets_shot_id'))
        batch_op.drop_index(batch_op.f('ix_screen_shot_assets_asset_version_id'))

    op.drop_table('screen_shot_assets')
    with op.batch_alter_table('screen_shots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_shots_status'))
        batch_op.drop_index(batch_op.f('ix_screen_shots_source_storyboard_panel_id'))
        batch_op.drop_index(batch_op.f('ix_screen_shots_shot_number'))
        batch_op.drop_index(batch_op.f('ix_screen_shots_scene_id'))
        batch_op.drop_index(batch_op.f('ix_screen_shots_position'))
        batch_op.drop_index(batch_op.f('ix_screen_shots_movement'))
        batch_op.drop_index(batch_op.f('ix_screen_shots_framing'))
        batch_op.drop_index(batch_op.f('ix_screen_shots_camera_angle'))
        batch_op.drop_index(batch_op.f('ix_screen_shots_approval'))

    op.drop_table('screen_shots')
    with op.batch_alter_table('screen_scene_characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_scene_characters_scene_id'))
        batch_op.drop_index(batch_op.f('ix_screen_scene_characters_entity_id'))

    op.drop_table('screen_scene_characters')
    with op.batch_alter_table('screen_scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_scenes_time_of_day'))
        batch_op.drop_index(batch_op.f('ix_screen_scenes_sequence_id'))
        batch_op.drop_index(batch_op.f('ix_screen_scenes_scene_number'))
        batch_op.drop_index(batch_op.f('ix_screen_scenes_production_status'))
        batch_op.drop_index(batch_op.f('ix_screen_scenes_position'))
        batch_op.drop_index(batch_op.f('ix_screen_scenes_environment'))

    op.drop_table('screen_scenes')
    with op.batch_alter_table('screen_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_sequences_unit_id'))
        batch_op.drop_index(batch_op.f('ix_screen_sequences_status'))
        batch_op.drop_index(batch_op.f('ix_screen_sequences_sequence_number'))
        batch_op.drop_index(batch_op.f('ix_screen_sequences_position'))

    op.drop_table('screen_sequences')
    with op.batch_alter_table('screen_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_units_unit_type'))
        batch_op.drop_index(batch_op.f('ix_screen_units_status'))
        batch_op.drop_index(batch_op.f('ix_screen_units_screen_project_id'))
        batch_op.drop_index(batch_op.f('ix_screen_units_position'))
        batch_op.drop_index(batch_op.f('ix_screen_units_number'))

    op.drop_table('screen_units')
    with op.batch_alter_table('screen_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_projects_title'))
        batch_op.drop_index(batch_op.f('ix_screen_projects_story_world_id'))
        batch_op.drop_index(batch_op.f('ix_screen_projects_status'))
        batch_op.drop_index(batch_op.f('ix_screen_projects_source_work_id'))
        batch_op.drop_index(batch_op.f('ix_screen_projects_format'))
        batch_op.drop_index(batch_op.f('ix_screen_projects_dossier_id'))

    op.drop_table('screen_projects')
    # ### end Alembic commands ###
