"""agent framework

Revision ID: 0008_agents
Revises: 0007_screen
Create Date: 2026-06-25 13:49:48.103271
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0008_agents'
down_revision: Union[str, None] = '0007_screen'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_templates_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_templates_key'), ['key'], unique=True)

    op.create_table('agent_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('requested_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='agentrunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('retry_of_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['retry_of_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_requested_by_id'), ['requested_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_retry_of_id'), ['retry_of_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_target_type'), ['target_type'], unique=False)

    op.create_table('prompt_template_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_template_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_template_versions_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_template_versions_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_template_versions_version'), ['version'], unique=False)

    op.create_table('agent_action_proposals',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('tool_key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='agentrisklevel'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXECUTED', 'FAILED', 'CANCELLED', name='proposalstatus'), nullable=False),
    sa.Column('approved_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_action_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_action_proposals_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_proposals_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_proposals_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_proposals_rejected_by_id'), ['rejected_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_proposals_requires_approval'), ['requires_approval'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_proposals_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_proposals_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_proposals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_proposals_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_proposals_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_proposals_tool_key'), ['tool_key'], unique=False)

    op.create_table('agent_findings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='findingseverity'), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_findings_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_findings_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_findings_resolved_by_id'), ['resolved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_findings_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_findings_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_findings_target_type'), ['target_type'], unique=False)

    # NOTE: works story_world_id / story_series_id / source_work_id were added
    # in 0002 deliberately without FK constraints (model-layer only). We do not
    # add them here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_findings_target_type'))
        batch_op.drop_index(batch_op.f('ix_agent_findings_target_id'))
        batch_op.drop_index(batch_op.f('ix_agent_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_agent_findings_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_findings_resolved_by_id'))
        batch_op.drop_index(batch_op.f('ix_agent_findings_resolved'))
        batch_op.drop_index(batch_op.f('ix_agent_findings_category'))
        batch_op.drop_index(batch_op.f('ix_agent_findings_agent_key'))

    op.drop_table('agent_findings')
    with op.batch_alter_table('agent_action_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_action_proposals_tool_key'))
        batch_op.drop_index(batch_op.f('ix_agent_action_proposals_target_type'))
        batch_op.drop_index(batch_op.f('ix_agent_action_proposals_target_id'))
        batch_op.drop_index(batch_op.f('ix_agent_action_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_agent_action_proposals_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_action_proposals_risk_level'))
        batch_op.drop_index(batch_op.f('ix_agent_action_proposals_requires_approval'))
        batch_op.drop_index(batch_op.f('ix_agent_action_proposals_rejected_by_id'))
        batch_op.drop_index(batch_op.f('ix_agent_action_proposals_approved_by_id'))
        batch_op.drop_index(batch_op.f('ix_agent_action_proposals_agent_key'))
        batch_op.drop_index(batch_op.f('ix_agent_action_proposals_action_type'))

    op.drop_table('agent_action_proposals')
    with op.batch_alter_table('prompt_template_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_template_versions_version'))
        batch_op.drop_index(batch_op.f('ix_prompt_template_versions_template_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_template_versions_created_by_id'))

    op.drop_table('prompt_template_versions')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_target_type'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_target_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_retry_of_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_key'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_key'))
        batch_op.drop_index(batch_op.f('ix_prompt_templates_enabled'))

    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
