"""operational integration hub

Revision ID: 0009_integrations
Revises: 0008_agents
Create Date: 2026-06-25 14:26:29.982759
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0009_integrations'
down_revision: Union[str, None] = '0008_agents'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_links',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('integration_point_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_kind', sa.Enum('COMMIT', 'ISSUE', 'PULL_REQUEST', 'BRANCH', 'RELEASE', 'OTHER', name='integrationlinkkind'), nullable=False),
    sa.Column('external_ref', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['integration_point_id'], ['integration_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_links_external_kind'), ['external_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_links_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_links_integration_point_id'), ['integration_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_links_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_links_target_type'), ['target_type'], unique=False)

    op.create_table('integration_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('integration_point_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adapter_key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='integrationrunstatus'), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requested_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('approval_proposal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_proposal_id'], ['agent_action_proposals.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['integration_point_id'], ['integration_points.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_runs_adapter_key'), ['adapter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_approval_proposal_id'), ['approval_proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_dry_run'), ['dry_run'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_integration_point_id'), ['integration_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_is_external'), ['is_external'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_rejected_by_id'), ['rejected_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_requested_by_id'), ['requested_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_requires_approval'), ['requires_approval'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_runs_status'), ['status'], unique=False)

    with op.batch_alter_table('integration_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adapter_key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True))
        # server_default backfills existing rows; the model carries no default
        # so it is ignored by the model/migration parity check.
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
        batch_op.add_column(sa.Column('credential_refs', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
        batch_op.create_index(batch_op.f('ix_integration_points_adapter_key'), ['adapter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_points_enabled'), ['enabled'], unique=False)

    # NOTE: works story_world_id / story_series_id / source_work_id were added
    # in 0002 deliberately without FK constraints (model-layer only). Alembic
    # keeps proposing them on every autogenerate; we intentionally do not add
    # them here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_points_enabled'))
        batch_op.drop_index(batch_op.f('ix_integration_points_adapter_key'))
        batch_op.drop_column('credential_refs')
        batch_op.drop_column('config')
        batch_op.drop_column('enabled')
        batch_op.drop_column('adapter_key')

    with op.batch_alter_table('integration_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_runs_status'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_requires_approval'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_rejected_by_id'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_operation'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_is_external'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_integration_point_id'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_dry_run'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_direction'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_approved_by_id'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_approval_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_integration_runs_adapter_key'))

    op.drop_table('integration_runs')
    with op.batch_alter_table('integration_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_links_target_type'))
        batch_op.drop_index(batch_op.f('ix_integration_links_target_id'))
        batch_op.drop_index(batch_op.f('ix_integration_links_integration_point_id'))
        batch_op.drop_index(batch_op.f('ix_integration_links_external_ref'))
        batch_op.drop_index(batch_op.f('ix_integration_links_external_kind'))

    op.drop_table('integration_links')
    # ### end Alembic commands ###
