"""operational business layer

Revision ID: 0010_business
Revises: 0009_integrations
Create Date: 2026-06-25 14:54:55.523962
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0010_business'
down_revision: Union[str, None] = '0009_integrations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Adding a column / FK to rights & contracts forces a SQLite table rebuild,
# which reflects the baseline's *unnamed* foreign keys. A naming convention lets
# the batch operation name them on the way through (same fix as 0002 / 0004).
NAMING = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_tags',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_tags_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_contact_tags_slug'), ['slug'], unique=True)

    op.create_table('organizations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=False),
    sa.Column('kind', sa.Enum('PUBLISHER', 'DISTRIBUTOR', 'PRINTER', 'RETAILER', 'FESTIVAL', 'AGENCY', 'MEDIA', 'STUDIO', 'INSTITUTION', 'OTHER', name='organizationkind'), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('source_of_introduction', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('source_of_introduction', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('relevant_work_ids', sa.JSON(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('consent_status', sa.Enum('UNKNOWN', 'GRANTED', 'DECLINED', 'WITHDRAWN', name='consentstatus'), nullable=False),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('preferred_channel', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('consent_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_consent_status'), ['consent_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_do_not_contact'), ['do_not_contact'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_follow_up_date'), ['follow_up_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_organization_id'), ['organization_id'], unique=False)

    op.create_table('contact_roles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('PUBLISHER', 'DISTRIBUTOR', 'PRINTER', 'JOURNALIST', 'REVIEWER', 'FESTIVAL', 'TRANSLATOR', 'ARTIST', 'AGENT', 'COLLABORATOR', 'EDITOR', 'RETAILER', 'OTHER', name='contactrolekind'), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_roles_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_roles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_roles_role'), ['role'], unique=False)

    op.create_table('contact_tag_links',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['contact_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_tag_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_tag_links_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_tag_links_tag_id'), ['tag_id'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('kind', sa.Enum('RIGHTS_SALE', 'CO_EDITION', 'TRANSLATION', 'REVIEW', 'FESTIVAL', 'DISTRIBUTION', 'COLLABORATION', 'SPONSORSHIP', 'OTHER', name='opportunitykind'), nullable=False),
    sa.Column('status', sa.Enum('LEAD', 'QUALIFIED', 'ACTIVE', 'NEGOTIATION', 'WON', 'LOST', 'DORMANT', name='opportunitystatus'), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_expected_close_date'), ['expected_close_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_work_id'), ['work_id'], unique=False)

    op.create_table('chain_of_title_entries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rights_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('CREATION', 'ASSIGNMENT', 'LICENSE', 'WORK_FOR_HIRE', 'INHERITANCE', 'REVERSION', 'OTHER', name='chainoftitletype'), nullable=False),
    sa.Column('from_party', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('to_party', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('instrument', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['rights_id'], ['rights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chain_of_title_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chain_of_title_entries_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_chain_of_title_entries_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chain_of_title_entries_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_chain_of_title_entries_rights_id'), ['rights_id'], unique=False)

    op.create_table('interactions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sa.Enum('EMAIL', 'CALL', 'MEETING', 'EVENT', 'SUBMISSION', 'SOCIAL', 'NOTE', 'OTHER', name='interactionkind'), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', 'INTERNAL', name='interactiondirection'), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachment_ref', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_follow_up_date'), ['follow_up_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_work_id'), ['work_id'], unique=False)

    op.create_table('rights_evidence',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rights_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('CONTRACT', 'AMENDMENT', 'ASSIGNMENT', 'REGISTRATION', 'CORRESPONDENCE', 'RELEASE', 'LICENSE', 'OTHER', name='rightsevidencekind'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_ref', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('dated_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['rights_id'], ['rights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rights_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rights_evidence_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_evidence_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_evidence_rights_id'), ['rights_id'], unique=False)

    op.create_table('rights_options',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rights_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('scope', sa.Enum('PRINT', 'EBOOK', 'AUDIOBOOK', 'FILM', 'TELEVISION', 'STAGE', 'TRANSLATION', 'SERIAL', 'ADAPTATION', 'MERCHANDISING', 'GAMING', 'ALL', 'OTHER', name='rightscope'), nullable=False),
    sa.Column('holder', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('option_start', sa.Date(), nullable=True),
    sa.Column('option_end', sa.Date(), nullable=True),
    sa.Column('exercise_deadline', sa.Date(), nullable=True),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'EXERCISED', 'EXPIRED', 'DECLINED', name='optionperiodstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['rights_id'], ['rights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rights_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rights_options_exercise_deadline'), ['exercise_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_options_option_end'), ['option_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_options_rights_id'), ['rights_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_options_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_options_status'), ['status'], unique=False)

    op.create_table('rights_status_history',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rights_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sa.Enum('PRINT', 'EBOOK', 'AUDIOBOOK', 'FILM', 'TELEVISION', 'STAGE', 'TRANSLATION', 'SERIAL', 'ADAPTATION', 'MERCHANDISING', 'GAMING', 'ALL', 'OTHER', name='rightscope'), nullable=False),
    sa.Column('from_status', sa.Enum('AVAILABLE', 'RESERVED', 'OPTIONED', 'LICENSED', 'SOLD', 'NOT_APPLICABLE', name='rightstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('AVAILABLE', 'RESERVED', 'OPTIONED', 'LICENSED', 'SOLD', 'NOT_APPLICABLE', name='rightstatus'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changed_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rights_id'], ['rights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rights_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rights_status_history_changed_by_id'), ['changed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_status_history_rights_id'), ['rights_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_status_history_scope'), ['scope'], unique=False)

    op.create_table('rights_windows',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rights_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sa.Enum('PRINT', 'EBOOK', 'AUDIOBOOK', 'FILM', 'TELEVISION', 'STAGE', 'TRANSLATION', 'SERIAL', 'ADAPTATION', 'MERCHANDISING', 'GAMING', 'ALL', 'OTHER', name='rightscope'), nullable=False),
    sa.Column('territory', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('exclusivity', sa.Enum('EXCLUSIVE', 'SOLE', 'NON_EXCLUSIVE', 'UNSPECIFIED', name='rightsexclusivity'), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'EXPIRED', 'TERMINATED', 'REVERTED', name='rightswindowstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['rights_id'], ['rights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rights_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rights_windows_ends_on'), ['ends_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_windows_rights_id'), ['rights_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_windows_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_windows_starts_on'), ['starts_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_windows_status'), ['status'], unique=False)

    op.create_table('editions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('production_record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('format', sa.Enum('HARDCOVER', 'TRADE_PAPERBACK', 'MASS_MARKET', 'POD_PAPERBACK', 'EBOOK', 'AUDIOBOOK', 'WEB_COMIC', 'PDF', 'BOX_SET', 'OTHER', name='editionformat'), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('territory', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('imprint', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('identifier_type', sa.Enum('ISBN_13', 'ISBN_10', 'ASIN', 'DOI', 'UPC', 'INTERNAL', 'NONE', name='editionidentifiertype'), nullable=False),
    sa.Column('trim_size', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('height_mm', sa.Float(), nullable=True),
    sa.Column('spine_mm', sa.Float(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('distribution_status', sa.Enum('PLANNED', 'IN_PREP', 'READY', 'SUBMITTED', 'LIVE', 'ON_HOLD', 'OUT_OF_PRINT', 'WITHDRAWN', name='distributionstatus'), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('edition_metadata', sa.JSON(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['production_record_id'], ['production_records.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('editions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_editions_distribution_status'), ['distribution_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_editions_format'), ['format'], unique=False)
        batch_op.create_index(batch_op.f('ix_editions_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_editions_identifier_type'), ['identifier_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_editions_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_editions_manuscript_id'), ['manuscript_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_editions_production_record_id'), ['production_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_editions_publication_date'), ['publication_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_editions_territory'), ['territory'], unique=False)
        batch_op.create_index(batch_op.f('ix_editions_work_id'), ['work_id'], unique=False)

    op.create_table('distribution_packages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('edition_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sa.Enum('ONIX', 'KDP', 'INGRAM', 'GLOBALCOMIX', 'PRESS_KIT', 'ARC', name='distributionchannel'), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'VALIDATED', 'INVALID', 'FAILED', name='packagestatus'), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generated_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distribution_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distribution_packages_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_packages_edition_id'), ['edition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_packages_generated_by_id'), ['generated_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_packages_status'), ['status'], unique=False)

    with op.batch_alter_table('contracts', schema=None, naming_convention=NAMING) as batch_op:
        batch_op.add_column(sa.Column('rights_holder', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
        batch_op.add_column(sa.Column('exclusivity', sa.Enum('EXCLUSIVE', 'SOLE', 'NON_EXCLUSIVE', 'UNSPECIFIED', name='rightsexclusivity'), nullable=False, server_default='UNSPECIFIED'))
        batch_op.add_column(sa.Column('effective_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('term_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('term_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('option_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('option_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('option_exercised', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('reversion_conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('reversion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sublicensable', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('territory_coverage', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('language_coverage', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.create_index(batch_op.f('ix_contracts_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_exclusivity'), ['exclusivity'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_option_end_date'), ['option_end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_reversion_date'), ['reversion_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_term_end_date'), ['term_end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_term_start_date'), ['term_start_date'], unique=False)

    with op.batch_alter_table('rights', schema=None, naming_convention=NAMING) as batch_op:
        batch_op.add_column(sa.Column('rights_holder', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
        batch_op.add_column(sa.Column('rights_holder_contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('exclusivity', sa.Enum('EXCLUSIVE', 'SOLE', 'NON_EXCLUSIVE', 'UNSPECIFIED', name='rightsexclusivity'), nullable=False, server_default='UNSPECIFIED'))
        batch_op.add_column(sa.Column('term_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('term_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sublicensable', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('sublicense_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('reversion_conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('reversion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('adaptation_constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('merchandising_constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('territory_coverage', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('language_coverage', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('reminder_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rights_exclusivity'), ['exclusivity'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_reminder_date'), ['reminder_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_reversion_date'), ['reversion_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_rights_holder_contact_id'), ['rights_holder_contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_sublicensable'), ['sublicensable'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_term_end_date'), ['term_end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rights_term_start_date'), ['term_start_date'], unique=False)
        batch_op.create_foreign_key(
            batch_op.f('fk_rights_rights_holder_contact_id_contacts'),
            'contacts', ['rights_holder_contact_id'], ['id'],
        )

    # NOTE: works story_world_id / story_series_id / source_work_id were added in
    # 0002 deliberately without FK constraints (model-layer only). Alembic keeps
    # proposing them on every autogenerate; we intentionally do not add them here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rights', schema=None, naming_convention=NAMING) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rights_term_start_date'))
        batch_op.drop_index(batch_op.f('ix_rights_term_end_date'))
        batch_op.drop_index(batch_op.f('ix_rights_sublicensable'))
        batch_op.drop_index(batch_op.f('ix_rights_rights_holder_contact_id'))
        batch_op.drop_index(batch_op.f('ix_rights_reversion_date'))
        batch_op.drop_index(batch_op.f('ix_rights_reminder_date'))
        batch_op.drop_index(batch_op.f('ix_rights_exclusivity'))
        batch_op.drop_column('reminder_date')
        batch_op.drop_column('language_coverage')
        batch_op.drop_column('territory_coverage')
        batch_op.drop_column('merchandising_constraints')
        batch_op.drop_column('adaptation_constraints')
        batch_op.drop_column('reversion_date')
        batch_op.drop_column('reversion_conditions')
        batch_op.drop_column('sublicense_terms')
        batch_op.drop_column('sublicensable')
        batch_op.drop_column('term_end_date')
        batch_op.drop_column('term_start_date')
        batch_op.drop_column('exclusivity')
        batch_op.drop_column('rights_holder_contact_id')
        batch_op.drop_column('rights_holder')

    with op.batch_alter_table('contracts', schema=None, naming_convention=NAMING) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_term_start_date'))
        batch_op.drop_index(batch_op.f('ix_contracts_term_end_date'))
        batch_op.drop_index(batch_op.f('ix_contracts_reversion_date'))
        batch_op.drop_index(batch_op.f('ix_contracts_option_end_date'))
        batch_op.drop_index(batch_op.f('ix_contracts_exclusivity'))
        batch_op.drop_index(batch_op.f('ix_contracts_effective_date'))
        batch_op.drop_column('language_coverage')
        batch_op.drop_column('territory_coverage')
        batch_op.drop_column('sublicensable')
        batch_op.drop_column('reversion_date')
        batch_op.drop_column('reversion_conditions')
        batch_op.drop_column('option_exercised')
        batch_op.drop_column('option_end_date')
        batch_op.drop_column('option_start_date')
        batch_op.drop_column('term_end_date')
        batch_op.drop_column('term_start_date')
        batch_op.drop_column('effective_date')
        batch_op.drop_column('exclusivity')
        batch_op.drop_column('rights_holder')

    with op.batch_alter_table('distribution_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distribution_packages_status'))
        batch_op.drop_index(batch_op.f('ix_distribution_packages_generated_by_id'))
        batch_op.drop_index(batch_op.f('ix_distribution_packages_edition_id'))
        batch_op.drop_index(batch_op.f('ix_distribution_packages_channel'))

    op.drop_table('distribution_packages')
    with op.batch_alter_table('editions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_editions_work_id'))
        batch_op.drop_index(batch_op.f('ix_editions_territory'))
        batch_op.drop_index(batch_op.f('ix_editions_publication_date'))
        batch_op.drop_index(batch_op.f('ix_editions_production_record_id'))
        batch_op.drop_index(batch_op.f('ix_editions_manuscript_id'))
        batch_op.drop_index(batch_op.f('ix_editions_language'))
        batch_op.drop_index(batch_op.f('ix_editions_identifier_type'))
        batch_op.drop_index(batch_op.f('ix_editions_identifier'))
        batch_op.drop_index(batch_op.f('ix_editions_format'))
        batch_op.drop_index(batch_op.f('ix_editions_distribution_status'))

    op.drop_table('editions')
    with op.batch_alter_table('rights_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rights_windows_status'))
        batch_op.drop_index(batch_op.f('ix_rights_windows_starts_on'))
        batch_op.drop_index(batch_op.f('ix_rights_windows_scope'))
        batch_op.drop_index(batch_op.f('ix_rights_windows_rights_id'))
        batch_op.drop_index(batch_op.f('ix_rights_windows_ends_on'))

    op.drop_table('rights_windows')
    with op.batch_alter_table('rights_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rights_status_history_scope'))
        batch_op.drop_index(batch_op.f('ix_rights_status_history_rights_id'))
        batch_op.drop_index(batch_op.f('ix_rights_status_history_changed_by_id'))

    op.drop_table('rights_status_history')
    with op.batch_alter_table('rights_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rights_options_status'))
        batch_op.drop_index(batch_op.f('ix_rights_options_scope'))
        batch_op.drop_index(batch_op.f('ix_rights_options_rights_id'))
        batch_op.drop_index(batch_op.f('ix_rights_options_option_end'))
        batch_op.drop_index(batch_op.f('ix_rights_options_exercise_deadline'))

    op.drop_table('rights_options')
    with op.batch_alter_table('rights_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rights_evidence_rights_id'))
        batch_op.drop_index(batch_op.f('ix_rights_evidence_kind'))
        batch_op.drop_index(batch_op.f('ix_rights_evidence_asset_id'))

    op.drop_table('rights_evidence')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_work_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_interactions_kind'))
        batch_op.drop_index(batch_op.f('ix_interactions_follow_up_date'))
        batch_op.drop_index(batch_op.f('ix_interactions_direction'))
        batch_op.drop_index(batch_op.f('ix_interactions_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_contact_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_asset_id'))

    op.drop_table('interactions')
    with op.batch_alter_table('chain_of_title_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chain_of_title_entries_rights_id'))
        batch_op.drop_index(batch_op.f('ix_chain_of_title_entries_position'))
        batch_op.drop_index(batch_op.f('ix_chain_of_title_entries_entry_type'))
        batch_op.drop_index(batch_op.f('ix_chain_of_title_entries_effective_date'))

    op.drop_table('chain_of_title_entries')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_work_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_title'))
        batch_op.drop_index(batch_op.f('ix_opportunities_status'))
        batch_op.drop_index(batch_op.f('ix_opportunities_owner_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_organization_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_kind'))
        batch_op.drop_index(batch_op.f('ix_opportunities_expected_close_date'))
        batch_op.drop_index(batch_op.f('ix_opportunities_contact_id'))

    op.drop_table('opportunities')
    with op.batch_alter_table('contact_tag_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_tag_links_tag_id'))
        batch_op.drop_index(batch_op.f('ix_contact_tag_links_contact_id'))

    op.drop_table('contact_tag_links')
    with op.batch_alter_table('contact_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_roles_role'))
        batch_op.drop_index(batch_op.f('ix_contact_roles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_contact_roles_contact_id'))

    op.drop_table('contact_roles')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_full_name'))
        batch_op.drop_index(batch_op.f('ix_contacts_follow_up_date'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_do_not_contact'))
        batch_op.drop_index(batch_op.f('ix_contacts_consent_status'))

    op.drop_table('contacts')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_kind'))
        batch_op.drop_index(batch_op.f('ix_organizations_country'))

    op.drop_table('organizations')
    with op.batch_alter_table('contact_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_tags_slug'))
        batch_op.drop_index(batch_op.f('ix_contact_tags_name'))

    op.drop_table('contact_tags')
    # ### end Alembic commands ###
