"""private curation of public reader

Revision ID: 0011_curation
Revises: 0010_business
Create Date: 2026-06-25 16:29:46.718527
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0011_curation'
down_revision: Union[str, None] = '0010_business'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Adding a FK column to public_hotspots forces a SQLite table rebuild, which
# reflects the baseline's unnamed foreign keys. A naming convention lets the
# batch operation name them on the way through (same fix as 0002 / 0004).
NAMING = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_approvals',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='publicationapprovalstatus'), nullable=False),
    sa.Column('requested_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['published_work_id'], ['published_works.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publication_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_approvals_decided_by_id'), ['decided_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_approvals_published_work_id'), ['published_work_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_approvals_requested_by_id'), ['requested_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_approvals_status'), ['status'], unique=False)

    op.create_table('publication_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'SCHEDULED', 'APPROVAL_REQUESTED', 'APPROVED', 'REJECTED', 'PUBLISHED', 'UNPUBLISHED', 'ARCHIVED', 'PAGE_HANDED_OFF', name='publicationaction'), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_status', sa.Enum('DRAFT', 'PUBLISHED', 'UNLISTED', 'ARCHIVED', name='publishedstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'PUBLISHED', 'UNLISTED', 'ARCHIVED', name='publishedstatus'), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['published_work_id'], ['published_works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publication_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_events_published_work_id'), ['published_work_id'], unique=False)

    op.create_table('published_panels',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('panel_number', sa.Integer(), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('focus_x', sa.Float(), nullable=True),
    sa.Column('focus_y', sa.Float(), nullable=True),
    sa.Column('focus_width', sa.Float(), nullable=True),
    sa.Column('focus_height', sa.Float(), nullable=True),
    sa.Column('transition', sa.Enum('CUT', 'FADE', 'DISSOLVE', 'SLIDE', 'ZOOM', name='paneltransition'), nullable=False),
    sa.Column('transition_duration_ms', sa.Integer(), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.Column('audio_track_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_panel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['audio_track_id'], ['public_media_assets.id'], ),
    sa.ForeignKeyConstraint(['published_page_id'], ['published_pages.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['public_media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('published_panels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_panels_panel_number'), ['panel_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_panels_published_page_id'), ['published_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_panels_reading_order'), ['reading_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_panels_source_panel_id'), ['source_panel_id'], unique=False)

    with op.batch_alter_table('public_hotspots', schema=None, naming_convention=NAMING) as batch_op:
        batch_op.add_column(sa.Column('published_panel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_public_hotspots_published_panel_id'), ['published_panel_id'], unique=False)
        batch_op.create_foreign_key(
            batch_op.f('fk_public_hotspots_published_panel_id_published_panels'),
            'published_panels', ['published_panel_id'], ['id'],
        )

    with op.batch_alter_table('published_pages', schema=None, naming_convention=NAMING) as batch_op:
        batch_op.add_column(sa.Column('source_gn_page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('source_asset_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_published_pages_source_asset_version_id'), ['source_asset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_pages_source_gn_page_id'), ['source_gn_page_id'], unique=False)

    # NOTE: works story_world_id / story_series_id / source_work_id were added in
    # 0002 deliberately without FK constraints (model-layer only). Alembic keeps
    # proposing them on every autogenerate; we intentionally do not add them here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('published_pages', schema=None, naming_convention=NAMING) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_pages_source_gn_page_id'))
        batch_op.drop_index(batch_op.f('ix_published_pages_source_asset_version_id'))
        batch_op.drop_column('source_asset_version_id')
        batch_op.drop_column('source_gn_page_id')

    with op.batch_alter_table('public_hotspots', schema=None, naming_convention=NAMING) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_hotspots_published_panel_id'))
        batch_op.drop_column('published_panel_id')

    with op.batch_alter_table('published_panels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_panels_source_panel_id'))
        batch_op.drop_index(batch_op.f('ix_published_panels_reading_order'))
        batch_op.drop_index(batch_op.f('ix_published_panels_published_page_id'))
        batch_op.drop_index(batch_op.f('ix_published_panels_panel_number'))

    op.drop_table('published_panels')
    with op.batch_alter_table('publication_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_events_published_work_id'))
        batch_op.drop_index(batch_op.f('ix_publication_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_publication_events_action'))

    op.drop_table('publication_events')
    with op.batch_alter_table('publication_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_publication_approvals_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_publication_approvals_published_work_id'))
        batch_op.drop_index(batch_op.f('ix_publication_approvals_decided_by_id'))

    op.drop_table('publication_approvals')
    # ### end Alembic commands ###
