"""brain persistence domain

Revision ID: 0014_brain
Revises: 0013_catalogue
Create Date: 2026-06-26 16:33:11.482619

Creates the SUPERVOID Brain persistence layer (9 tables): the current compiled
states (studio / project), the immutable revision history, the append-only
domain-event log, conversations / messages / checkpoints, durable memory items
and decision records. Storage only — no state is compiled here.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0014_brain'
down_revision: Union[str, None] = '0013_catalogue'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_brain_states',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('singleton_key', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPILING', 'READY', 'STALE', 'FAILED', name='brainstatestatus'), nullable=False),
    sa.Column('compiled_at', sa.DateTime(), nullable=True),
    sa.Column('source_event_cursor', sa.Integer(), nullable=False),
    sa.Column('structured_state', sa.JSON(), nullable=False),
    sa.Column('compact_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('compiler_version', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('assist_version', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton_key')
    )
    with op.batch_alter_table('studio_brain_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_brain_states_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_brain_states_source_event_cursor'), ['source_event_cursor'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_brain_states_stale'), ['stale'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_brain_states_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_brain_states_version'), ['version'], unique=False)

    op.create_table('brain_state_revisions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('state_type', sa.Enum('STUDIO', 'PROJECT', name='brainstatetype'), nullable=False),
    sa.Column('state_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_version', sa.Integer(), nullable=True),
    sa.Column('deterministic_payload', sa.JSON(), nullable=False),
    sa.Column('llm_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_event_from', sa.Integer(), nullable=True),
    sa.Column('source_event_to', sa.Integer(), nullable=True),
    sa.Column('compiler_version', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('approval_status', sa.Enum('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED', name='brainrevisionapproval'), nullable=False),
    sa.Column('approved_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brain_state_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brain_state_revisions_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_state_revisions_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_state_revisions_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_state_revisions_source_event_to'), ['source_event_to'], unique=False)
        batch_op.create_index('ix_brain_state_revisions_state', ['state_type', 'state_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_state_revisions_state_id'), ['state_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_state_revisions_state_type'), ['state_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_state_revisions_version'), ['version'], unique=False)

    op.create_table('brain_conversations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('librechat_conversation_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('active_profile', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='brainconversationstatus'), nullable=False),
    sa.Column('last_state_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story_world_id'], ['story_worlds.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brain_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brain_conversations_librechat_conversation_id'), ['librechat_conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_conversations_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_conversations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_conversations_story_world_id'), ['story_world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_conversations_work_id'), ['work_id'], unique=False)

    op.create_table('brain_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('aggregate_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('aggregate_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='braineventstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story_world_id'], ['story_worlds.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brain_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brain_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index('ix_brain_events_aggregate', ['aggregate_type', 'aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_events_aggregate_id'), ['aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_events_aggregate_type'), ['aggregate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_events_sequence'), ['sequence'], unique=True)
        batch_op.create_index(batch_op.f('ix_brain_events_status'), ['status'], unique=False)
        batch_op.create_index('ix_brain_events_status_sequence', ['status', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_events_story_world_id'), ['story_world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_events_work_id'), ['work_id'], unique=False)

    op.create_table('project_brain_states',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPILING', 'READY', 'STALE', 'FAILED', name='brainstatestatus'), nullable=False),
    sa.Column('compiled_at', sa.DateTime(), nullable=True),
    sa.Column('source_event_cursor', sa.Integer(), nullable=False),
    sa.Column('structured_state', sa.JSON(), nullable=False),
    sa.Column('compact_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canon_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('production_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('priorities', sa.JSON(), nullable=False),
    sa.Column('recent_changes', sa.JSON(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['story_world_id'], ['story_worlds.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_brain_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_brain_states_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_brain_states_source_event_cursor'), ['source_event_cursor'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_brain_states_stale'), ['stale'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_brain_states_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_brain_states_story_world_id'), ['story_world_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_brain_states_version'), ['version'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_brain_states_work_id'), ['work_id'], unique=True)

    op.create_table('brain_messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM', 'USER', 'ASSISTANT', 'TOOL', name='brainmessagerole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('structured_content', sa.JSON(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('state_version', sa.Integer(), nullable=True),
    sa.Column('retrieval_ids', sa.JSON(), nullable=False),
    sa.Column('tool_call_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['brain_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brain_messages', schema=None) as batch_op:
        batch_op.create_index('ix_brain_messages_conversation_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_messages_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_messages_role'), ['role'], unique=False)

    op.create_table('decision_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('scope', sa.Enum('STUDIO', 'PROJECT', 'MEMBER', 'CONVERSATION', name='brainscope'), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=False),
    sa.Column('affected_entities', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='decisionstatus'), nullable=False),
    sa.Column('source_conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proposer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approver_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('superseded_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['brain_conversations.id'], ),
    sa.ForeignKeyConstraint(['story_world_id'], ['story_worlds.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['decision_records.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_records_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_proposer_id'), ['proposer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_scope'), ['scope'], unique=False)
        batch_op.create_index('ix_decision_records_scope_status', ['scope', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_source_conversation_id'), ['source_conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_story_world_id'), ['story_world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_superseded_by_id'), ['superseded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_work_id'), ['work_id'], unique=False)

    op.create_table('brain_checkpoints',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('prompt_template_version', sa.Integer(), nullable=True),
    sa.Column('studio_state_version', sa.Integer(), nullable=True),
    sa.Column('project_state_version', sa.Integer(), nullable=True),
    sa.Column('last_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context_checksum', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('prefix_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sa.Enum('WARM', 'COLD', name='braincheckpointstatus'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['brain_conversations.id'], ),
    sa.ForeignKeyConstraint(['last_message_id'], ['brain_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brain_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brain_checkpoints_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_checkpoints_last_message_id'), ['last_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_checkpoints_last_used_at'), ['last_used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_checkpoints_prefix_hash'), ['prefix_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_checkpoints_status'), ['status'], unique=False)

    op.create_table('brain_memory_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('scope', sa.Enum('STUDIO', 'PROJECT', 'MEMBER', 'CONVERSATION', name='brainscope'), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('member_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sa.Enum('FACT', 'PREFERENCE', 'PROCEDURE', 'DECISION', 'UNRESOLVED_QUESTION', 'COMMITMENT', name='brainmemorykind'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verification', sa.Enum('UNVERIFIED', 'VERIFIED', 'REJECTED', 'SUPERSEDED', 'EXPIRED', name='brainmemoryverification'), nullable=False),
    sa.Column('supersedes_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['brain_conversations.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['brain_events.id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['brain_messages.id'], ),
    sa.ForeignKeyConstraint(['story_world_id'], ['story_worlds.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['brain_memory_items.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brain_memory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brain_memory_items_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_member_user_id'), ['member_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_source_event_id'), ['source_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_source_message_id'), ['source_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_story_world_id'), ['story_world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_supersedes_id'), ['supersedes_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_verification'), ['verification'], unique=False)
        batch_op.create_index(batch_op.f('ix_brain_memory_items_work_id'), ['work_id'], unique=False)

    # NOTE: works.source_work_id / story_world_id / story_series_id were added in
    # 0002 deliberately WITHOUT FK constraints (model-layer only). Autogenerate
    # wants to add them; we do not (consistent with the 0008 note).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brain_memory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_work_id'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_verification'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_story_world_id'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_source_message_id'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_scope'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_kind'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_expires_at'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_brain_memory_items_approved_by_id'))

    op.drop_table('brain_memory_items')
    with op.batch_alter_table('brain_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brain_checkpoints_status'))
        batch_op.drop_index(batch_op.f('ix_brain_checkpoints_prefix_hash'))
        batch_op.drop_index(batch_op.f('ix_brain_checkpoints_last_used_at'))
        batch_op.drop_index(batch_op.f('ix_brain_checkpoints_last_message_id'))
        batch_op.drop_index(batch_op.f('ix_brain_checkpoints_conversation_id'))

    op.drop_table('brain_checkpoints')
    with op.batch_alter_table('decision_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_records_work_id'))
        batch_op.drop_index(batch_op.f('ix_decision_records_superseded_by_id'))
        batch_op.drop_index(batch_op.f('ix_decision_records_story_world_id'))
        batch_op.drop_index(batch_op.f('ix_decision_records_status'))
        batch_op.drop_index(batch_op.f('ix_decision_records_source_conversation_id'))
        batch_op.drop_index('ix_decision_records_scope_status')
        batch_op.drop_index(batch_op.f('ix_decision_records_scope'))
        batch_op.drop_index(batch_op.f('ix_decision_records_proposer_id'))
        batch_op.drop_index(batch_op.f('ix_decision_records_approver_id'))

    op.drop_table('decision_records')
    with op.batch_alter_table('brain_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brain_messages_role'))
        batch_op.drop_index(batch_op.f('ix_brain_messages_request_id'))
        batch_op.drop_index(batch_op.f('ix_brain_messages_conversation_id'))
        batch_op.drop_index('ix_brain_messages_conversation_created')

    op.drop_table('brain_messages')
    with op.batch_alter_table('project_brain_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_brain_states_work_id'))
        batch_op.drop_index(batch_op.f('ix_project_brain_states_version'))
        batch_op.drop_index(batch_op.f('ix_project_brain_states_story_world_id'))
        batch_op.drop_index(batch_op.f('ix_project_brain_states_status'))
        batch_op.drop_index(batch_op.f('ix_project_brain_states_stale'))
        batch_op.drop_index(batch_op.f('ix_project_brain_states_source_event_cursor'))
        batch_op.drop_index(batch_op.f('ix_project_brain_states_checksum'))

    op.drop_table('project_brain_states')
    with op.batch_alter_table('brain_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brain_events_work_id'))
        batch_op.drop_index(batch_op.f('ix_brain_events_story_world_id'))
        batch_op.drop_index('ix_brain_events_status_sequence')
        batch_op.drop_index(batch_op.f('ix_brain_events_status'))
        batch_op.drop_index(batch_op.f('ix_brain_events_sequence'))
        batch_op.drop_index(batch_op.f('ix_brain_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_brain_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_brain_events_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_brain_events_aggregate_type'))
        batch_op.drop_index(batch_op.f('ix_brain_events_aggregate_id'))
        batch_op.drop_index('ix_brain_events_aggregate')
        batch_op.drop_index(batch_op.f('ix_brain_events_actor_id'))

    op.drop_table('brain_events')
    with op.batch_alter_table('brain_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brain_conversations_work_id'))
        batch_op.drop_index(batch_op.f('ix_brain_conversations_story_world_id'))
        batch_op.drop_index(batch_op.f('ix_brain_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_brain_conversations_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_brain_conversations_librechat_conversation_id'))

    op.drop_table('brain_conversations')
    with op.batch_alter_table('brain_state_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brain_state_revisions_version'))
        batch_op.drop_index(batch_op.f('ix_brain_state_revisions_state_type'))
        batch_op.drop_index(batch_op.f('ix_brain_state_revisions_state_id'))
        batch_op.drop_index('ix_brain_state_revisions_state')
        batch_op.drop_index(batch_op.f('ix_brain_state_revisions_source_event_to'))
        batch_op.drop_index(batch_op.f('ix_brain_state_revisions_generated_at'))
        batch_op.drop_index(batch_op.f('ix_brain_state_revisions_approved_by_id'))
        batch_op.drop_index(batch_op.f('ix_brain_state_revisions_approval_status'))

    op.drop_table('brain_state_revisions')
    with op.batch_alter_table('studio_brain_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_brain_states_version'))
        batch_op.drop_index(batch_op.f('ix_studio_brain_states_status'))
        batch_op.drop_index(batch_op.f('ix_studio_brain_states_stale'))
        batch_op.drop_index(batch_op.f('ix_studio_brain_states_source_event_cursor'))
        batch_op.drop_index(batch_op.f('ix_studio_brain_states_checksum'))

    op.drop_table('studio_brain_states')
    # ### end Alembic commands ###
