"""studio constitution and instruction layer

Revision ID: 7f9b734958ac
Revises: 0015_brain_outbox
Create Date: 2026-06-26 19:24:22.863313
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types, e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '0016_constitution'
down_revision: Union[str, None] = '0015_brain_outbox'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_profiles_enabled'), 'assistant_profiles', ['enabled'], unique=False)
    op.create_index(op.f('ix_assistant_profiles_key'), 'assistant_profiles', ['key'], unique=True)
    op.create_table('context_templates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_templates_enabled'), 'context_templates', ['enabled'], unique=False)
    op.create_index(op.f('ix_context_templates_key'), 'context_templates', ['key'], unique=True)
    op.create_table('safety_approval_policies',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_approval_policies_enabled'), 'safety_approval_policies', ['enabled'], unique=False)
    op.create_index(op.f('ix_safety_approval_policies_key'), 'safety_approval_policies', ['key'], unique=True)
    op.create_table('studio_constitutions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_constitutions_enabled'), 'studio_constitutions', ['enabled'], unique=False)
    op.create_index(op.f('ix_studio_constitutions_key'), 'studio_constitutions', ['key'], unique=True)
    op.create_table('terminology_glossaries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminology_glossaries_enabled'), 'terminology_glossaries', ['enabled'], unique=False)
    op.create_index(op.f('ix_terminology_glossaries_key'), 'terminology_glossaries', ['key'], unique=True)
    op.create_table('assistant_profile_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permitted_domains', sa.JSON(), nullable=False),
    sa.Column('required_project_scope', sa.Boolean(), nullable=False),
    sa.Column('available_tools', sa.JSON(), nullable=False),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_format', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('approval_policy', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('default_temperature', sa.Float(), nullable=False),
    sa.Column('output_limit', sa.Integer(), nullable=False),
    sa.Column('model_preference', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('required_scopes', sa.JSON(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['assistant_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_profile_versions_created_by_id'), 'assistant_profile_versions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_assistant_profile_versions_profile_id'), 'assistant_profile_versions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_assistant_profile_versions_version'), 'assistant_profile_versions', ['version'], unique=False)
    op.create_table('context_template_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('segment_key', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['context_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_template_versions_created_by_id'), 'context_template_versions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_context_template_versions_segment_key'), 'context_template_versions', ['segment_key'], unique=False)
    op.create_index(op.f('ix_context_template_versions_template_id'), 'context_template_versions', ['template_id'], unique=False)
    op.create_index(op.f('ix_context_template_versions_version'), 'context_template_versions', ['version'], unique=False)
    op.create_table('safety_approval_policy_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('AUTO', 'REQUIRE_REVIEW', 'REQUIRE_APPROVE', 'OWNER_ONLY', name='safetyapprovalmode'), nullable=False),
    sa.Column('required_scope_to_act', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('blocked_tools', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['safety_approval_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_approval_policy_versions_created_by_id'), 'safety_approval_policy_versions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_safety_approval_policy_versions_mode'), 'safety_approval_policy_versions', ['mode'], unique=False)
    op.create_index(op.f('ix_safety_approval_policy_versions_policy_id'), 'safety_approval_policy_versions', ['policy_id'], unique=False)
    op.create_index(op.f('ix_safety_approval_policy_versions_version'), 'safety_approval_policy_versions', ['version'], unique=False)
    op.create_table('studio_constitution_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('constitution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['constitution_id'], ['studio_constitutions.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studio_constitution_versions_constitution_id'), 'studio_constitution_versions', ['constitution_id'], unique=False)
    op.create_index(op.f('ix_studio_constitution_versions_created_by_id'), 'studio_constitution_versions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_studio_constitution_versions_version'), 'studio_constitution_versions', ['version'], unique=False)
    op.create_table('terminology_glossary_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('glossary_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['glossary_id'], ['terminology_glossaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminology_glossary_versions_created_by_id'), 'terminology_glossary_versions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_terminology_glossary_versions_glossary_id'), 'terminology_glossary_versions', ['glossary_id'], unique=False)
    op.create_index(op.f('ix_terminology_glossary_versions_version'), 'terminology_glossary_versions', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terminology_glossary_versions_version'), table_name='terminology_glossary_versions')
    op.drop_index(op.f('ix_terminology_glossary_versions_glossary_id'), table_name='terminology_glossary_versions')
    op.drop_index(op.f('ix_terminology_glossary_versions_created_by_id'), table_name='terminology_glossary_versions')
    op.drop_table('terminology_glossary_versions')
    op.drop_index(op.f('ix_studio_constitution_versions_version'), table_name='studio_constitution_versions')
    op.drop_index(op.f('ix_studio_constitution_versions_created_by_id'), table_name='studio_constitution_versions')
    op.drop_index(op.f('ix_studio_constitution_versions_constitution_id'), table_name='studio_constitution_versions')
    op.drop_table('studio_constitution_versions')
    op.drop_index(op.f('ix_safety_approval_policy_versions_version'), table_name='safety_approval_policy_versions')
    op.drop_index(op.f('ix_safety_approval_policy_versions_policy_id'), table_name='safety_approval_policy_versions')
    op.drop_index(op.f('ix_safety_approval_policy_versions_mode'), table_name='safety_approval_policy_versions')
    op.drop_index(op.f('ix_safety_approval_policy_versions_created_by_id'), table_name='safety_approval_policy_versions')
    op.drop_table('safety_approval_policy_versions')
    op.drop_index(op.f('ix_context_template_versions_version'), table_name='context_template_versions')
    op.drop_index(op.f('ix_context_template_versions_template_id'), table_name='context_template_versions')
    op.drop_index(op.f('ix_context_template_versions_segment_key'), table_name='context_template_versions')
    op.drop_index(op.f('ix_context_template_versions_created_by_id'), table_name='context_template_versions')
    op.drop_table('context_template_versions')
    op.drop_index(op.f('ix_assistant_profile_versions_version'), table_name='assistant_profile_versions')
    op.drop_index(op.f('ix_assistant_profile_versions_profile_id'), table_name='assistant_profile_versions')
    op.drop_index(op.f('ix_assistant_profile_versions_created_by_id'), table_name='assistant_profile_versions')
    op.drop_table('assistant_profile_versions')
    op.drop_index(op.f('ix_terminology_glossaries_key'), table_name='terminology_glossaries')
    op.drop_index(op.f('ix_terminology_glossaries_enabled'), table_name='terminology_glossaries')
    op.drop_table('terminology_glossaries')
    op.drop_index(op.f('ix_studio_constitutions_key'), table_name='studio_constitutions')
    op.drop_index(op.f('ix_studio_constitutions_enabled'), table_name='studio_constitutions')
    op.drop_table('studio_constitutions')
    op.drop_index(op.f('ix_safety_approval_policies_key'), table_name='safety_approval_policies')
    op.drop_index(op.f('ix_safety_approval_policies_enabled'), table_name='safety_approval_policies')
    op.drop_table('safety_approval_policies')
    op.drop_index(op.f('ix_context_templates_key'), table_name='context_templates')
    op.drop_index(op.f('ix_context_templates_enabled'), table_name='context_templates')
    op.drop_table('context_templates')
    op.drop_index(op.f('ix_assistant_profiles_key'), table_name='assistant_profiles')
    op.drop_index(op.f('ix_assistant_profiles_enabled'), table_name='assistant_profiles')
    op.drop_table('assistant_profiles')
    # ### end Alembic commands ###
